### ISSUE TITLE
Cannot connect to servers

### ISSUE THREAD

**Issue by Matvei27** [alterstep/dnscrypt-osxclient#102]
I am unable to connect to most servers, while a few are working just fine. All of the servers were working for me until the other day. I am using the Mac version and I have ipv6 disabled.
Connecting to servers which previously worked fine now results in dnscrypt showing "Standby"
I do not think it is an issue with the server has it is happening with multiple servers hosted by multiple providers.

**Comment by alterstep** [comment]
Which ones are working and which ones are not?
