### ISSUE TITLE
Always Standby - "configuration seems to be hijacking HTTP queries" says log

### ISSUE THREAD

**Issue by GAhlekzis** [alterstep/dnscrypt-osxclient#103]
Hello. 
I installed the client a few days ago and today it stopped working. 
It cycles back and forth between standard DNS and my selected DNScrypt server.
Log says everything is cool until "Current configuration seems to be hijacking HTTP queries. Reverting to default resolvers."
and starts the cycle again.

Here is the full log:
[dnscrypt-osxclient-debug.txt](https://github.com/alterstep/dnscrypt-osxclient/files/295614/dnscrypt-osxclient-debug.txt)

**Comment by alterstep** [comment]
Did you change anything to your router/firewall or did you install software such as little snitch?

The message appears if the Apple website doesn't load any more or doesn't contain "apple" in it.

**Comment by GAhlekzis** [comment]
I don't use these kinds of software except for turning my firewall *on*.

But lucky for both of us, I enabled DNSCrypt today because you reminded me of it and it magically works right now.
