### ISSUE TITLE
Jerky scrolling

### ISSUE THREAD

**Issue by keirthomas** [alterstep/dnscrypt-osxclient#104]
This might sound a little incredible but DNSCrypt causes jerky scrolling for me in Safari (15in MacBook Pro mid-2015; Safari 9.1.1 (11601.6.17))). Not all the time but every now and again. I haven't spotted any kind of pattern. 

Console isn't reporting anything other than perhaps this as a cause: 

WindowServer[175]: _CGXRemoveWindowFromWindowMovementGroup: window 0x2f is not attached to window 0x31

Uninstall DNSCrypt and scrolling is smooth again. 
Install DNSCrypt and I get intermittent jerky scrolling. 

No other signs of issues. The page is loading correctly.

**Comment by alterstep** [comment]
This is probably unrelated, and I can't reproduce it.
