### ISSUE TITLE
Missing connections for Little Snitch

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [alterstep/dnscrypt-osxclient#106]
The About tab in the preference pane lists several addresses that are supposed to be allowed in Little Snitch, but there were two requests made that aren't listed:

_curl tried to establish a connection to download.dnscrypt.org on TCP port 443_

_DNSCrypt Menubar via curl tried to establish a connection to download.dnscrypt.org on TCP port 80_

The About tab says
> Using Little Snitch? There are a few rules you need to establish, which Little Snitch should prompt for when trying to activate this application:
Allow any outgoing connection for system processes (dnscrypt-proxy)
Allow any incoming connection for system process (dnscrypt-proxy)
Allow any outgoing connection for system processes (dig)
Allow outgoing TCP connections to port 80 (http) of www.apple.com for system process (curl)
For automatic updates, allow outgoing TCP connections to port 80 (http) of updates.dnscrypt.org and to port 443 (https) of github.com for system process (curl)

Evidently some addresses were either omitted or have changed, and should be added to the list in the next update.

**Comment by alterstep** [comment]
It was added 2 weeks ago.
