### ISSUE TITLE
Problem with DHCP DNS servers and DNSCrypt bypass

### ISSUE THREAD

**Issue by jomo** [alterstep/dnscrypt-osxclient#108]
The script `exceptions-add.sh` creates DNSCrpyt exceptions by creating `/etc/resolver/$domain` with a specific resolv config. It gets the name_server to be used as follows:
```shell
get_dhcp_dns() {
  cat "${STATES_DIR}/dhcp-dns" 2> /dev/null
}

# ...

name_servers=$(./get-static-resolvers.sh || get_dhcp_dns || get_gw)
```

The dhcp-dns file is written by `check-network-change.sh`, which is only executed by `handle-network-change.sh` if called with `--boot` *and* `$FALLBACK_FILE` exists. Having a quick look at the code, I think this file only exists when the `Automatically disable if blocked` checkbox is ticked.

As a result, `name_servers` falls back to the gateway instead of using the DHCP DNS servers

**Comment by alterstep** [comment]
>  Having a quick look at the code, I think this file only exists when the Automatically disable if blocked checkbox is ticked.

No.

**Comment by jomo** [comment]
Maybe I am wrong, the problem does still exist however. DHCP DNS works as expected with the check box ticket.

Where else is this file created?

**Comment by jomo** [comment]
I just tried this again:

- `Automatically disable if blocked` is **not** ticked
- No static resolvers are configured
- Multiple resolvers are provided via DHCP (the gateway IP is not among them)
- `example.com` is configured as exception
- The `$FALLBACK_FILE` (`/Library/Application Support/DNSCrypt/control/fallback`) does not exist
- The dhcp-dns file (`/Library/Application Support/DNSCrypt/states/dhcp-dns`) does not exist
- The `/etc/resolver/example.com` file only has the gateway configured as nameserver.
  - As a result, I can't reach (resolve) example.com.

After ticking `Automatically disable if blocked` the fallback file exists, the dhcp-dns file exists with proper resolvers, and `/etc/resolver/example.com` has those dhcp resolvers configured properly.

----

I also checked the source code again and could only find one instance where [the fallback file is created](https://github.com/alterstep/dnscrypt-osxclient/blob/795f1f6259f33901c5fc21c780dfd71ee5f0d94b/DNSCrypt-Preference-Pane/DNSCrypt/extra/usr/scripts/switch-fallback-on.sh#L5), namely in `switch-fallback-on.sh`. This file is executed in the [setFallbackOn method](https://github.com/alterstep/dnscrypt-osxclient/blob/795f1f6259f33901c5fc21c780dfd71ee5f0d94b/DNSCrypt-Preference-Pane/DNSCrypt/DNSCrypt.m#L201):

```shell
/bin/csh -f -c "cd '/Library/PreferencePanes/DNSCrypt.prefPane/Contents/Resources/usr/bin/scripts' && ./create-ticket.sh && ./switch-fallback-on.sh"
```

The `setFallbackOn` method itself is [only exectuted](https://github.com/alterstep/dnscrypt-osxclient/blob/795f1f6259f33901c5fc21c780dfd71ee5f0d94b/DNSCrypt-Preference-Pane/DNSCrypt/DNSCrypt.m#L230) in `fallbackButtonPressed` when the checkbox is ticked.

----

Regardless of the file being created or not, the exception domains aren't configured to use a proper resolver if the checkbox is not ticked.

----

@alterstep Can you re-open this issue, please? If you still think this should remain closed, could you provide more reason than "No."?

**Comment by jomo** [comment]
This is still a problem, please re-open.

**Comment by jomo** [comment]
Still happening with the latest version. Would you like me to send a pull request?

**Comment by pannous** [comment]
still not resolved, please re-open
@jomo please send pull request

**Comment by jomo** [comment]
Sorry, not going to send a PR until @alterstep at least acknowledges that this problem exists

**Comment by imkebe** [comment]
I have same problem with latest 1.0.14 version. Bypass doesn't work. I have default settings only done wildcard domain (*.rdgis.loc) is provided in Bypass DNSCrypt section. DHCP provide default DNS servers and resolve that domain only when DNSCrypt disabled.

**Comment by jomo** [comment]
@imkebe DNSCrypt bypassing is realized using macOS internals by creating a file in `/etc/resolver/$domain`. This does not supports wildcard names, but you can use `rdgis.loc` to get the same result.  
See SEARCH STRATEGY in [`resolver(5)`](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man5/resolver.5.html):

> For example, […] a search for "x.a.b.c" would use the "a.b.c" resolver configuration
