### ISSUE TITLE
1.0.12 Bypassing DNSCrypt for domains stopt working 

### ISSUE THREAD

**Issue by pilldriver** [alterstep/dnscrypt-osxclient#112]
In the latest version bypassing DNSCrypt for domains doesn't work anymore.

As soon as i disable DNSCrypt the (local) domains get resolved but when DNSCrypt is active they don't get the expected bypass.

This worked in the previous version, don't know what changed but somehow they are ignored!

![dnscrypt](https://cloud.githubusercontent.com/assets/6171488/18228135/5718c7e8-723f-11e6-8c4a-4f8fccdc48f9.png)

**Comment by pilldriver** [comment]
Figured it out already, neet to set my network on static and then it works.

**Comment by pannous** [comment]
Same issue here 

what do you mean by static?

**Comment by pannous** [comment]
What ever the solution I think this should be reopened and be made available via GUI

**Comment by pannous** [comment]
Solved by adding the local router to
/Library/Application\ Support/DNSCrypt/control/static-resolvers

**Comment by pannous** [comment]
see #108
