### ISSUE TITLE
Does not appear to work with fresh Sierra install

### ISSUE THREAD

**Issue by sergeb** [alterstep/dnscrypt-osxclient#114]
I tried it on two macs, one Sierra upgrade and one fresh install. The upgrade which had dnscrypt, works fine. The fresh install does not. It never connects and the DNS in the network settings always points to what was assigned on the LAN.

**Comment by diligiant** [comment]
same here ; it works sometimes and inconsistently across the 3 machines I got it installed on.

**Comment by Influxx** [comment]
Same problem here on Sierra (upgraded from El Capitan - running on MBPro 2015). Was working perfectly fine before the upgrade, but now it simply won't connect to any resolver anymore. I also see that the resolvers don't correspond anymore with the update list from https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-resolvers.csv

Screenshot:
https://i.gyazo.com/aed4681f40710e3cbfba148f7bbaa50c.png

If there's anything I can help to debug, let me know. I need this app in my life.

**Comment by DotTheI** [comment]
It works for me. However, it stops working once I delete the 'DNSCrypt Menubar' from Applications (without deleting the Settings bundle). Would be nice to not to have the item in Applications.

**Comment by marcus-cr** [comment]
I don't have any issues running on Sierra after upgrade, however I installed DNSCrypt after the fact.

**Comment by sergeb** [comment]
It's only an issue on fresh installs, on the machines I've done.

**Comment by marcus-cr** [comment]
@sergeb I probably should've elaborated further. I upgraded to Sierra, then installed DNSCrypt for the first time ever without issues. I didn't use DNSCrypt before Sierra.

**Comment by chew-z** [comment]
I have similar problem. Sometimes DNSCrypt-OSX Client goes into crazy infinite loop starting DNSCrypt again and again.

**Comment by jedisct1** [comment]
Works for me on Sierra, except when virtual machines are running at the same time (see the mDNSResponder issue, that also affects dnssec-trigger).

**Comment by LightMoon** [comment]
@marcus-cr
I have exactly the same problem

**Comment by bnchndlr** [comment]
I installed, however it would immediately crash on turning DNS crypt on. I would get the black screen of death and then it would fail on reboot each time.

**Comment by halimsujanto** [comment]
@bnchndlr Maybe because you have little snitch running as well. I deleted littlesnitch and able to run dnscrypt, but since I'm on fresh install Sierra, dnscrypt still not working.
