### ISSUE TITLE
Request for Manual Settings Update

### ISSUE THREAD

**Issue by marcus-cr** [alterstep/dnscrypt-osxclient#115]
Hello,

Just making a minor request to include the option to manually update DNSCrypt when changing (advanced) options.

DNSCrypt updates the (advanced) settings and alters my DNS servers even when DNSCrypt is disabled.

This has been an issue while connected to a VPN using their DNS servers. Simply clicking any of the fields without making changes will update DNSCrypt and overwrite my (VPN) DNS servers when connected.

**Comment by chew-z** [comment]
+1

**Comment by marcus-cr** [comment]
Without a Apple Developer account I can't make any adjustments on the preference pane. Trying to reconfigure was also a pain. Ended up abandoning for the CLI version of dnscrypt-proxy and configured with new listening port. [https://github.com/jedisct1/dnscrypt-proxy/issues/477](url)
