### ISSUE TITLE
System DNS settings get overwritten

### ISSUE THREAD

**Issue by DotTheI** [alterstep/dnscrypt-osxclient#120]
DNSCrypt, obviously, overwrites system DNS settings. However, when it's turned off, the settings that had been used before it was turned off reset to default, i.e. 192.168.2.1, not the ones that I entered manually.

**Comment by alterstep** [comment]
You can use static IP addresses instead of the one from the router!

Open the preference pane and in the Advanced tab, enter the IP addresses in the "use the following static DNS servers" form field.
