### ISSUE TITLE
typo in the uninstall script..

### ISSUE THREAD

**Issue by ealmonte32** [alterstep/dnscrypt-osxclient#121]
Hi, I havent checked the install package script, but it seems the uninstall script contains the line:
launch remove com.github.dnscryot-osxclient.DNSCryptAfterboot with the typo dnscryot rather than saying dnscrypt.
Just thought I'd bring that to your attention.

![typo-in-script](https://cloud.githubusercontent.com/assets/24350198/20857157/9877e680-b8f1-11e6-828e-64e5f21a2e98.png)

**Comment by alterstep** [comment]
good eyesight thank you!
