### ISSUE TITLE
DNSCrypt and 10.12.2 don't play nicely together.

### ISSUE THREAD

**Issue by D1001** [alterstep/dnscrypt-osxclient#123]
@alterstep 

![screen shot 2016-12-13 at 6 37 41 pm](https://cloud.githubusercontent.com/assets/8568087/21164048/b34d93d0-c164-11e6-94a6-53a99aa20bc2.png)

It shows that DNScrypt is active, but as you can see the box isn't checked and it doesn't resolve any sites. I'm also unable to change any resolvers.

Edit: Seems to be working fine again with 10.12.3 Beta (16D12b).

**Comment by mw3demo** [comment]
Uninstalling DNSCrypt and Reinstalling fixes the issue. No need to update to 10.12.3 Beta.
