### ISSUE TITLE
Doesn’t reconnect after waking from sleep

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [alterstep/dnscrypt-osxclient#125]
Almost every time my computer wakes up from sleep mode, the app fails to connect.
I must uncheck/re-check the **_Enable_** menu item, then it connects.

OS X 10.11.6
DNSCrypt 1.0.12

**Comment by myhro** [comment]
I have a problem that resembles this: DNSCrypt does reconnect after wake up and I'm able to use it as expected. The only problem is that the domains in the bypass list aren't resolved anymore. After unchecking/re-checking the `Enable DNSCrypt` option, they start working again.

@alterstep should I create a new issue? Or can we reopen this one?
