### ISSUE TITLE
Unreliable/Stops Working

### ISSUE THREAD

**Issue by Haravikk** [alterstep/dnscrypt-osxclient#126]
I've been trying for a little while now to use DNS Crypt via the OS X GUI distribution (as a menubar widget and preference pane), however I've found it be far too unreliable.

At least once a day it just locks up and stops responding entirely, forcing me to disable and re-enable DNS Crypt. It doesn't seem to matter which resolver I'm using.

Today this went a step further and I just couldn't get it to work at all, forcing me to go into my network interfaces and manually remove the 127.0.0.1 entry from the DNS servers list, i.e; the preference pane was no longer doing this automatically.

The process seems to keep running, it just won't respond to queries anymore. Like I say, usually disabling and re-enabling it works but that didn't work at all today which has forced me to go back to using my ISP's DNS service for now until I can find some way to determine what's wrong.

I'm running macOS El Capitan (all updates installed) in case that matters.

**Comment by Haravikk** [comment]
Why was this closed? The issue never went away, I had to uninstall it completely.

However, using dnscrypt-proxy directly (installed via MacPorts) works perfectly, so there's definitely something odd about dnscrypt-osxclient.

I'm wondering if it might have something to do with my having multiple users on the same system? So sometimes more than one is logged in at a time, each with its own dnscrypt menubar widget. dnscrypt-proxy meanwhile is just the one, constant process launched at boot so has no other components to fail.

**Comment by alterstep** [comment]
Try the new version.
