### ISSUE TITLE
[Failed] com.github.dnscrypt-osxclient.DNSCryptConsoleChange.plist

### ISSUE THREAD

**Issue by jprokos** [alterstep/dnscrypt-osxclient#128]
Not sure this is an issue,,, I am running EtreCheck and seeing this Launch Daemon is failing to launch.

OSX 10.12.3

**Comment by pbGuy** [comment]
When I see this EtreCheck result, which does not always occur, a Restart usually loads this plist. Running EtreCheck again will confirm.

**Comment by alterstep** [comment]
It's because the script runs quickly: it only changes the permissions on a directory so it is fast.
EtreCheck thinks that it's an error because it was fast but it is not!
