### ISSUE TITLE
Won't work on MacOS 10.12.3

### ISSUE THREAD

**Issue by alex2408** [alterstep/dnscrypt-osxclient#129]
Although I enabled DNSCrypt, my own IP is shown.

![schermafbeelding 2017-02-05 om 10 13 37](https://cloud.githubusercontent.com/assets/7881914/22625079/7b57b580-eb8c-11e6-9b68-0f304ea3e333.jpg)

**Comment by nsouch** [comment]
Hi, I also had a similar problem. After some debugging it appears that the ports 5004 or 5005 used by try_resolver in start-dnscrypt-proxy.sh are already in use by process CoreMIDI.framework/MIDIServer. I fixed the problem by changing them to 7004 and 7005.

Regards.

**Comment by alterstep** [comment]
thank you nsouch I didn't see that because I don't use midi. I removed the tests now it doesn't require ports.
