### ISSUE TITLE
Screenshots are not up to date

### ISSUE THREAD

**Issue by jedisct1** [alterstep/dnscrypt-osxclient#130]
You made quite a few significant changes to the control panel in version 1.0.13, so you should update the screenshots accordingly.

**Comment by jedisct1** [comment]
Also, these screenshots are blurry on a retina screen.

That's what you get for nuking my code. New issues on GitHub :)

**Comment by alterstep** [comment]
My revenge: that one is for you and you will not like it: #133

**Comment by mkjaer** [comment]
I created a [pull request](https://github.com/alterstep/dnscrypt-osxclient/pull/140) to fix this.
