### ISSUE TITLE
Installer : This user interface doesn't work with this version of OSX

### ISSUE THREAD

**Issue by diligiant** [alterstep/dnscrypt-osxclient#131]
I can't update on both my 2 machines. I am running Sierra 10.12.3!

**Comment by alterstep** [comment]
What do you mean?

**Comment by diligiant** [comment]
I get this installer "error" message (select destination step - volume with yellow warning triangle) with both dmg automatically downloaded or dwld'ed from github (not that it mattered but I tried!)

**Comment by alterstep** [comment]
Do you have OSX server?

**Comment by diligiant** [comment]
Genuine Sierra for those two. I was about to test with a third one, Server this time.

**Comment by alterstep** [comment]
I remade the package, can you try to download it again directly on GitHub?

**Comment by diligiant** [comment]
thank you ;)
