### ISSUE TITLE
_clock_gettime not found on MacOS 10.11.6

### ISSUE THREAD

**Issue by Thireus** [alterstep/dnscrypt-osxclient#133]
Just updated to 1.0.13 from 1.0.12 on MacOS 10.11.6. It's now impossible to enable dnscrypt, the process is crashing. Please find below one of many crash reports generated.

It seems the issue is due to a symbol that can't be resolved: "_clock_gettime"

```
Process:               dnscrypt-proxy [2678]
OS Version:            Mac OS X 10.11.6 (15G1217)

Dyld Error Message:
  Symbol not found: _clock_gettime
  Referenced from: /Library/PreferencePanes/DNSCrypt.prefPane/Contents/Resources/usr/sbin/dnscrypt-proxy
  Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by alterstep** [comment]
I remade the package. Could you download the dmg file again, directly from GitHub?

If it doesnt work I will block its usage on old versions (< 10.12 right now) because I can't test other versions than the one I run on my laptop. I don't have a dev machine.

**Comment by Thireus** [comment]
It's working now, thank you!

**Comment by jedisct1** [comment]
Arrrrrrgh, I hate these compatibility issues as well.

Once again, Apple adds new APIs and allows us to link against them even when using `-mmacosx-version-min` to explicitly ask for compatibility with old MacOS versions.

This affects libevent, too. Checked ldns as well, and by chance, that one doesn't use that function.

Even more annoying: the iOS builds might be affected as well, if Apple did the same thing on iOS, which is very likely.

Crap.

Maybe we have to pretend the function doesn't exist (in the autoconf scripts) if it's compiled for an Apple machine (`"$host_vendor" = "apple"`)?

I don't like that. Having to degrade the performance on current versions of the operating system for the sake of supporting old versions. I hate the idea, but to be honest, the performance drop will be totally negligible.

**Comment by alterstep** [comment]
Cisco and Yandex make money with software taking advantage of dnscrypt they could offer us a dev machine :dream:

**Comment by jedisct1** [comment]
Dream on, dreamer.

I made the change to the proxy:
https://github.com/jedisct1/dnscrypt-proxy/commit/449d0f0741ac1de7ae2e1f79c15fe736589fbdb0
