### ISSUE TITLE
Mac Os problem

### ISSUE THREAD

**Issue by pedinil** [alterstep/dnscrypt-osxclient#139]
dear developer

i have mac os with sierra version 10.12.3
 and i have osclient version 1.0.14

some time when i want to enable the checkbox , it dose not work , and some time when it is disable i want to enable also does not work
from the attachment you can see , the checkbox is not enable but it is enable 

<img width="358" alt="screen shot 2017-02-16 at 9 02 32 am" src="https://cloud.githubusercontent.com/assets/25811564/23008708/b1721af0-f426-11e6-9548-db56ac2c00df.png">

**Comment by alterstep** [comment]
Please read the FAQ.
