### ISSUE TITLE
New client blocking traffic

### ISSUE THREAD

**Issue by kurianjacob** [alterstep/dnscrypt-osxclient#142]
DNS traffic is no longer flowing after installing 1.0.14. App icon shows as connected but no website loads. Tried connecting to different servers but still same result. Had no issues with 1.0.13/12. Traffic flows again after disabling DNSCrypt client.

I am running OS X 10.12.3
Disabled A/V (Avast) but no change
OS X firewall is allowing traffic to the DNSCrypt app
Attached debug log 
[Dnscrypt log.txt](https://github.com/alterstep/dnscrypt-osxclient/files/791461/Dnscrypt.log.txt)

Thanks

 

*****************************************************************************************************************

Before creating an issue, please read the FAQ: https://github.com/alterstep/dnscrypt-osxclient/blob/master/FAQ.md

Informations and debug logs as explained here are almost always more useful that screenshots!

Thank you!

*****************************************************************************************************************

**Comment by phillycheeze** [comment]
I am also having the same issue. 

This happens on 10.12, and usually after the computer goes to sleep and wakes back up. I toggle the Enable checkbox, the resolver, and the enable ipv6 checkbox. Any combination still says that DNScrypt is "enabled" with a green shield. I couldn't disable it and nothing would resolve.

I uninstalled it and things are back to normal again.

**Comment by kurianjacob** [comment]
I uninstalled the client and reinstalled it. Now it seems to be working again. Not sure what caused the issues earlier. I am connecting via some of the anycast servers.
