### ISSUE TITLE
dnscrypt-osxclient-1.0.14.dmg.minisig: No such file or directory

### ISSUE THREAD

**Issue by pgeorgan** [alterstep/dnscrypt-osxclient#160]
Following your instructions for verification and this is all I get. 
`dnscrypt-osxclient-1.0.14.dmg.minisig: No such file or directory`
I am able to independently sign and verify a simple myfile.txt example. What am I missing? 

*****************************************************************************************************************

Before creating an issue, please read the FAQ: https://github.com/alterstep/dnscrypt-osxclient/blob/master/FAQ.md

Informations and debug logs as explained here are almost always more useful that screenshots!

Thank you!

*****************************************************************************************************************

**Comment by reelsense** [comment]
Make sure you downloaded the [`.minisig`](https://github.com/alterstep/dnscrypt-osxclient/releases/download/1.0.14/dnscrypt-osxclient-1.0.14.dmg.minisig) file and that it's in the correct directory.

**Comment by pgeorgan** [comment]
`Untrusted signature comment should start with "untrusted comment: "`

**Comment by reelsense** [comment]
I downloaded `dnscrypt-osxclient-1.0.14.dmg` to my _Downloads_ folder, so:

`cd ~/Downloads`

```
minisign -V -P RWRvw8aArS/yEI3In0/zQSb9+qfWonLxjjEYG17cXt6zct6GLKtEvUfk -m dnscrypt-osxclient-1.0.14.dmg
```
```
Signature and comment signature verified
Trusted comment: dnscrypt-osxclient-1.0.14.dmg
```

**Comment by reelsense** [comment]
If you're still having problems this string will download `dnscrypt-osxclient-1.0.14.dmg` to your temp folder, verify the signature, and then open the temp folder so you can grab the verified `.dmg` file. 

Copy and paste the whole string below into your terminal _(tripple-click & copy)_:

```
cd /tmp ; curl -OL https://github.com/alterstep/dnscrypt-osxclient/releases/download/1.0.14/dnscrypt-osxclient-1.0.14.dmg ; curl -OL https://github.com/alterstep/dnscrypt-osxclient/releases/download/1.0.14/dnscrypt-osxclient-1.0.14.dmg.minisig ; minisign -V -P RWRvw8aArS/yEI3In0/zQSb9+qfWonLxjjEYG17cXt6zct6GLKtEvUfk -m dnscrypt-osxclient-1.0.14.dmg ; open .
```

The files will be gone on reboot if you leave them in temp. So drag them to your desktop.

---

If you were using `curl` to fetch the releases you had to add `-L` to handle the Github redirect.

**Comment by pgeorgan** [comment]
Thx.
