### ISSUE TITLE
Auto-enable on specific networks

### ISSUE THREAD

**Issue by rasky** [alterstep/dnscrypt-osxclient#25]
I need dnscrypt to avoid filtering made by my home ISP, but I don't need it when I'm at work (in fact, I can't use it, I must use the local DNS there for accessing local resources). For my use case, it would be super useful an option to have it always off, and configured it to auto-enable whenever I'm connected to a list of specific WiFi networks.

**Comment by alterstep** [comment]
Control Plane is very good!
This is a good way to do it. I don't want to add to much complexity in the dnscrypt interface by reinventing  this as Control Plane works well.
