### ISSUE TITLE
Security related question: Is there are warning when certificate or anything else is wrong?!

### ISSUE THREAD

**Issue by therealmarv** [alterstep/dnscrypt-osxclient#30]
This is not an issue itself and I do not know how to simulate this conditions because of my lack of knowledge but for me this is really important and you should maybe add this to your README (maybe even with screenshots):

Is the dnscrypt osxclient warning or give me an error when the public key on the dnscrypt server is wrong when there is e.g. a man in the middle attack? Attacks like these [here](http://blog.zimperium.com/doubledirect-zimperium-discovers-full-duplex-icmp-redirect-attacks-in-the-wild/) show how DNS can be redirected and I wonder if this client show me an attack when the dnscrypt server is responding but the public key is wrong? Or do I only get an error to connect?

**Comment by alterstep** [comment]
Correct!
