### ISSUE TITLE
Does/could this interfere with Internet Sharing?

### ISSUE THREAD

**Issue by telomere** [alterstep/dnscrypt-osxclient#31]
I can't get OS X's Internet Sharing to work (share net on WiFi to Ethernet). I wonder could this be blocking it in some way?
I have seen a [stack exchange thread](https://apple.stackexchange.com/questions/125372/internet-sharing-handing-out-wrong-dns-server-address) that brought to mind that DNS _might_ be an issue for Internet Sharing. 
Is anyone using this able to use Internet Sharing successfully?

**Comment by alterstep** [comment]
It shouldn't interfere at all!
