### ISSUE TITLE
CFNetwork SSLHandshake failed

### ISSUE THREAD

**Issue by Tetonne** [alterstep/dnscrypt-osxclient#33]
in /var/log/system.log
i have many ocspd[219]: CFNetwork SSLHandshake failed (-9806)

any idea?

**Comment by alterstep** [comment]
Hi there!

dnscrypt does not use SSL. It doesn't use ocspd either.
You might have some issues reaching some certification authority, but it has nothing to do with dnscrypt or with dns at all :)
