### ISSUE TITLE
Please PGP sign the binary releases in future? 

### ISSUE THREAD

**Issue by telomere** [alterstep/dnscrypt-osxclient#34]
I'd really appreciate if you could sign the releases. I think its crucial for a security app like this that the end user can be certain that the app download is as the developer made it.[1] 

[1] http://arstechnica.com/security/2015/02/psa-your-crypto-apps-are-useless-unless-you-check-them-for-backdoors/

**Comment by alterstep** [comment]
Hello telomere,

The releases are signed already! Not using PGP, but using Apple's code signing system.

I understand that some people check the "install programs from unidentified developers" box, but if they do, are they going to use PGP? I doubt it :)

**Comment by telomere** [comment]
Fair enough. But I would have thought the opposite. I would guess the more advanced users on OSX  have that setting selected cause they install a lot of apps from GitHub etc. And yet I think they would use PGP signature if available. But if its too much trouble, its no problem.

**Comment by wilfreddekok** [comment]
I agree with @telomere and would also appreciate if you could sign your (release-)commits with your (Open)PGP key. Just add -S to your git-commit command.

Be sure to check out [this in depth guide by Mike Gerwitz](http://mikegerwitz.com/papers/git-horror-story).

**Comment by duanewilliams** [comment]
My Mac doesn't believe the release is signed at all.  I get the warning:  "“DNSCrypt.mpkg” can’t be opened because the identity of the developer cannot be confirmed."

**Comment by jedisct1** [comment]
The releases are signed. I signed them, but my Mac Developer Account expired, which is probably why you are now seeing the message that says the identity of the developer cannot be confirmed.

Unless someone who paid their $99 to Apple to be able to sign apps can help, having the files signed with PGP is more than mandatory.

**Comment by alterstep** [comment]
I created a PGP key, and the new release is signed!
