### ISSUE TITLE
Standby / Blank Current DNS settings.  OS X 10.10.2, Client UI 1.0.5

### ISSUE THREAD

**Issue by CheLucero** [alterstep/dnscrypt-osxclient#35]
DNSCrypt works when I'm on wi-fi, but not when I'm on my wired network. I am at a research institution, and the relevant machine is an iMac.

Some symptoms while on the wired network:
Can't do DNS lookup when DNSCrypt is enabled. The general tab in the UI lists status as 'Standby' when I enable DNSCrypt / red shield. 'Current DNS settings' are blank.

If I disable DNSCrypt, my DNS settings have been wiped out, but re-adding a server (such as 8.8.8.8) immediately makes DNS lookups work agai.n

I can make DNSCrypt work on the wired network like this:
1. Unplug wired network.
2. Turn on wifi (actually, wifi can already be on at step 1)
3. Let DNSCrypt begin working
4. Replug wired network
5. Disconnect wifi.

If the ethernet cable is plugged in when the wifi is turned on (ie step 1 is skipped), it will not work.

Wi-Fi is DHCP, ethernet is manually configured with a static IP.

Any ideas?

Thanks!

**Comment by alterstep** [comment]
The interface assumes that you are using DHCP.

It does not work with a static IP address because it's fairly complicated to restore the previous configuration.

Maybe in a future version, but until then your best option is to directly run the proxy and configure your DNS settings to 127.0.0.1

**Comment by sergeb** [comment]
A lot of institutions firewall this stuff, exclude all and only allow what
is known. I see it again and again. I don't think it's a bug.

Serge

**Comment by CheLucero** [comment]
I don't see how the data is amenable to a firewall explanation.
