### ISSUE TITLE
Auto-Update using Sparkle

### ISSUE THREAD

**Issue by hbarn** [alterstep/dnscrypt-osxclient#37]
I just realized I was running 1.0.4, two months after 1.0.5 was released.

Do you have any plans to include Sparkle or other auto-update functionality in DNSCrypt?

If a security vulnerability were discovered then auto-update would be the quickest way to push out a patched version.

**Comment by alterstep** [comment]
Sparkle is for applications written in Objective-C, but that one is written in Shell scripts.

I released a new version, 1.0.8, that can now update itself.
Compared to Spark, it's very simple (just one script), but it does the job and to some extent, it's even better than Spark.
Of course, files are digitally signed and verified.
