### ISSUE TITLE
Sign Installer with Certificate?

### ISSUE THREAD

**Issue by hbarn** [alterstep/dnscrypt-osxclient#38]
Would it be possible for you to sign the binary installer with an Apple app certificate?

It would avoid having to go into System Preferences to launch the app.

![screen shot 2015-02-20 at 5 49 48 pm](https://cloud.githubusercontent.com/assets/11097736/6310838/1192960c-b929-11e4-8c93-f3f46766d8c6.png)

**Comment by jedisct1** [comment]
I used to sign this app, but the signature expired.

This requires paying $99/year to Apple, which I can't afford any more.

Maybe somebody else with a Mac Developer account can help and sign these packages.

**Comment by alterstep** [comment]
It has been signed with PGP + Apple.
