### ISSUE TITLE
Causes Server Connection Issues

### ISSUE THREAD

**Issue by filmpro08** [alterstep/dnscrypt-osxclient#39]
I installed dnscrypt in OSX 10.10.2 on two different computers. Once the second computer one has the software installed I get a repeating error message that a network server can not be connected. There is no shortcut, no startup item, no login item, etc set up to connect to this second computer. Message goes away when dnscrypt is uninstalled. Has anyone run into this? Is this related to dnscrypt, or is dnscrypt revealing another system issue? Thank you!

**Comment by alterstep** [comment]
It doesn't sound like something related to dnscrypt.
