### ISSUE TITLE
requests :)

### ISSUE THREAD

**Issue by Tetonne** [alterstep/dnscrypt-osxclient#40]
- toggle in prefpane to use or not DNSCrypt in combination with a DNS cache 
- warning for available update in prefpane

Thanks for this great software

**Comment by alterstep** [comment]
DNS Cache, yes! I had planned to bundle a cache a long time ago, but I still haven't done it. This is still in my list of things to do as soon as possible.

Warning for available update -> go download version 1.0.8 and you have it! Not in the prefpane, but in the notification center, and the file is downloaded and saved on the desktop.

**Comment by Tetonne** [comment]
thanks for that :)
have a good WE
