### ISSUE TITLE
Support for command line or scripting

### ISSUE THREAD

**Issue by hostmaster** [alterstep/dnscrypt-osxclient#43]
dnscrypt is not working well with openvpn. It would be very useful if I could create a script in OpenVPN/Tunnelblick to disable/enable  DNSCrypt when vpn connection is up/down

**Comment by alterstep** [comment]
`dnscrypt-osxclient` intentionally disables dnscrypt when using a VPN.

If you use a VPN, dnscrypt should not be used, as the VPN already encrypts everything, including DNS traffic.

**Comment by jedisct1** [comment]
If my memory serves me correctly, Tunnelblick and OpenVPN have an option to avoid changing the resolvers to the ones supplied by the VPN provider.

That said, it's indeed a terrible idea to mix a VPN with DNSCrypt. It makes things slow, and if you use a VPN for privacy, sending extra copies of your activity elsewhere totally defeats the point.

**Comment by alterstep** [comment]
Scripts can control `dnscrypt-osxclient`.

In fact, the software is written in shell, with the exception of the proxy.

The `/Library/Application Support/DNSCrypt/control` directory is watched for changes.

If you create a file called `dnscrypt` here, it will enable dnscrypt. Delete the file, it will disable dnscrypt.

**Comment by hostmaster** [comment]
@alterstep as far as I can see it is not. probably timeout is quite big.

**Comment by hostmaster** [comment]
@alterstep That is great.  I will test you suggestion.

**Comment by alterstep** [comment]
By the way all the scripts live in `/Library/PreferencePanes/DNSCrypt.prefPane/Contents/Resources/usr/scripts`

As an alternative to create/delete the file yourself, you can call `switch-to-dhcp.sh` or `switch-to-dnscrypt.sh`. But creating/deleting the file is also what they do.

**Comment by hostmaster** [comment]
I've made two scripts for Tunnelblick I hope they would be useful https://gist.github.com/hostmaster/10b5f2f9a2b8fd3e276e
