### ISSUE TITLE
DNS connection issues

### ISSUE THREAD

**Issue by hp7** [alterstep/dnscrypt-osxclient#45]
Slow responses and connection drops
Traceroute sample

Traceroute has started…

traceroute to 216.70.98.201 (216.70.98.201), 64 hops max, 72 byte packets
 1  192.168.7.1 (192.168.7.1)  1.011 ms  0.528 ms  0.508 ms
 2  l100.nycmny-vfttp-129.verizon-gni.net (71.183.105.1)  5.083 ms  4.652 ms  5.076 ms
 3  g0-11-2-1.nycmny-lcr-21.verizon-gni.net (130.81.107.182)  9.868 ms  9.645 ms  10.115 ms
 4  * * *
 5  * * *
 6  0.ae7.gw10.ewr6.alter.net (140.222.231.129)  5.866 ms  7.206 ms  7.270 ms
 7  teliasonera-gw.customer.alter.net (157.130.91.86)  10.106 ms  9.262 ms  10.085 ms
 8  nyk-bb1-link.telia.net (213.155.130.29)  7.379 ms  7.058 ms  7.461 ms
 9  ash-bb3-link.telia.net (62.115.134.111)  14.954 ms  14.494 ms  14.980 ms
10  ash-b1-link.telia.net (80.91.248.161)  15.163 ms  14.265 ms  14.918 ms
11  net2ez-ic-152340-ash-bb1.c.telia.net (213.155.129.78)  15.104 ms  16.857 ms  14.966 ms
12  cr02-1-1.iad1.netdc.com (65.97.48.254)  14.960 ms  17.040 ms  24.966 ms
13  65.97.50.26 (65.97.50.26)  14.961 ms  14.471 ms  14.972 ms
14  e1.4.as02.iad01.mtsvc.net (70.32.64.246)  17.630 ms  24.291 ms  24.998 ms
15  vzx212.mediatemple.net (216.70.96.11)  14.975 ms  14.448 ms  15.012 ms

**Comment by alterstep** [comment]
Good morning!
What is this IP address you are trying to reach, `216.70.98.201`? Is it a dnscrypt server? I don't see it anywhere.

**Comment by hp7** [comment]
It is actually 
216.70.98.204
Didn't want the IP out there for others to keep pinging 
Had issues with other Servers from different locations. Not sure what is causing it. When I uninstall seems to resolve issue

**Comment by alterstep** [comment]
Thank you for following up.

Apparently, `216.70.98.204` is not running any DNS server either. What am I supposed to see on this IP and in this `traceroute` command?

This software only changes your DNS settings and doesn't do anything else that could possibly affect other protocols or the way packets are routed to an IP address.

**Comment by hp7** [comment]
It looks like it hangs when hitting your server in the trace route

**Comment by alterstep** [comment]
I don't have a server and I don't know what this IP address is!

I would recommend looking at the list of public dnscrypt servers and picking one that is close to your location and has the features you are looking for.

**Comment by hp7** [comment]
I'm sorry 
I saw
Alter.net
As the hop after the long lag and thought it was tied to DNS crypt
