### ISSUE TITLE
Majority of nameservers in DNSCrypt Pref Pane do not work, provide new list or UI to manually add a server

### ISSUE THREAD

**Issue by grempe** [alterstep/dnscrypt-osxclient#48]
I was trying today to switch from OpenDNS over IPv6 (works) in the Advanced tab of the pref pane to another DNS server. Specifically I wanted to try any of the OpenNIC servers listed. Sadly none of them seem to be functional which is likely due to this list being quite out of date. I could connect to the listed DNScrypt servers, but sadly none of them are in my country which will introduce latency issues.

Out of curiosity I tried many more of the servers in the list and found that a majority of them just won't ever successfully connect.

The client should be updated with a list of known working servers, and if that is too hard to maintain you should just eliminate the list and provide the UI to allow manual entry of DNS servers to a local list where I could provide the details needed (name, key, IP address, etc) and choose between servers in my own local list. Maybe that is pre-populated with a single known working server that is likely to continue working like OpenDNS.

Thank you.

**Comment by DavidStaron** [comment]
I agree, it's confusing because now you download a program that doesn't (seem to) work..

By the way fyi, i just noticed an up-to-date version of the .csv is available here: https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv

**Comment by alterstep** [comment]
Hi everybody.

Can you try the new version I just uploaded, 1.0.6?

Among other improvements, the list of resolvers is now automatically updated!

**Comment by DavidStaron** [comment]
Installed and it works.. thanks!

**Comment by grempe** [comment]
Installed and a quick spot check shows lots of working servers.  A quick look at the code though shows you seem to be downloading the server list over an HTTP (not HTTPS) connection. I tried changing your URL to https and testing it locally and it seems there is a TLS certificate mis-match on that download server.  Might be worth contacting them upstream to see about getting a proper working TLS URL to avoid MITM issues.

https://github.com/alterstep/dnscrypt-osxclient/commit/1b53464c9ab4bdb28eb74d2009ba2d647f3b97b4

Other than that this is a nice improvement.  Thanks for digging in.  I look forward to the next release (I see you have in progress).

**Comment by alterstep** [comment]
@grempe Look closer :smile:

https://github.com/alterstep/dnscrypt-osxclient/blob/master/DNSCrypt-Preference-Pane/DNSCrypt/extra/usr/scripts/update-resolvers-list.sh

It doesn't download only the file, but also the signature, and checks that the signature is valid before updating the file. HTTPS is not required, and this is even more secure that way.

**Comment by jedisct1** [comment]
...but you don't verify the metadata. The "trusted comment" includes a time stamp that you might want to compare against the previous one in order to prevent downgrades. And it wouldn't hurt to also check the file name, still part of the trusted comment. This is not critical, but these signed metadata are the main reason I wrote minisign and it makes me sad that you are not using them.

**Comment by alterstep** [comment]
Will do. Thanks.
