### ISSUE TITLE
Automatically "switch" if blocked

### ISSUE THREAD

**Issue by DavidStaron** [alterstep/dnscrypt-osxclient#50]
While using dnscrypt-osxclient I noticed that relying on a single Dns server caused frequent interruptions of my internet connection because it's temporarily unavailable for whatever reason.

When using dnscrypt-proxy you can run for example 3 instances on 127.0.0.1, 127.0.0.2, 127.0.0.3 and set all 3 as DNS servers on your host. When server 1 is (temporarily) unavailable, OS X will automatically switch to the next one. Using this method solved the connectivity problems i had.

When using dnscrypt-osxclient, configuring multiple DNS servers seems not possible. I think it might be good to implement a feature to "Automatically switch if blocked": to switch to another Dnscrypt name server when the current one is not working..

Next question would be of course, switch to which one? maybe add checkboxes?

**Comment by therealmarv** [comment]
I agree on this. This is actually the main reason I do not use dnscrypt-osxclient at home and only while traveling. Even the best dnscrypt servers tend to **fail** or **timeout** from time to time (even OpenDNS) and then I have to switch manually. I can only speculate but I think this are DDoS attacks.
So it works surely over 98% of time but then a DNScrypt server fails without warning... so I can always not be sure when I surf the web and do not get a webpage if the webserver is misbehaving or my DNScrypt server is not responding (I have to check two things).

I do not know what the best solution for this would be though.

**Comment by jomo** [comment]
I have a very similar issue because I'm often switching networks, and some networks don't support IPv6.
I have configured an IPv6 name server, which obviously doesn't work on IPv4-only networks.

It would be nice to have a fallback option. Should I open another issue for that?

**Comment by jedisct1** [comment]
Why use an IPv6 name server?

IPv4 name servers can resolve the same things, including IPv6 addresses.

**Comment by jomo** [comment]
Because I only have IPv4 access via a CGNAT, which often breaks and is generally slower than IPv6.

**Comment by 9Pigs** [comment]
Perhaps the same issue I'm seeing with the new 1.0.9 on my Yosemite system. Loss of connectivity, OpenDNS error, sluggish operation (better than no connection) when I changed which *single* DNSCrypt server.
   I found that I had to redo my OpenDNS server settings in my network preferences (after painfully removing DNSCrypt) to get my machine back on line.
   A few OS's back, when it was available via the OpenDNS webpage, it did not interfere with performance. What happened?

**Comment by alterstep** [comment]
@9Pigs This package is easy to remove: in the preferences pane, open the "About" tab and press the "Uninstall" button.
If you did it in a different way, try that way so that it correctly removes leftovers from previous versions, and then you can reinstall it.
Maybe the OpenDNS DNSCrypt server is overloaded these days. Try a different one.

**Comment by jomo** [comment]
@alterstep could we have a setting for an IPv4 *and* an IPv6 resolver, though? [see my comment above](#issuecomment-114077770)

**Comment by therealmarv** [comment]
so this issue is just closed? How about allowing multiple dnscrypt servers like you can do on normal DNS. It is sad that dnscrypt is overall not as reliable as a normal DNS because of wacky DNS servers. :( For me this is a really big issue and no. 1 reason not to use dnscrypt.

**Comment by alterstep** [comment]
If you can contribute the code and it's good, I will merge it. But I don't have time/motivation to do it, sorry.

**Comment by therealmarv** [comment]
no sorry, thanks for your work @alterstep ! I will see what I can do in my spare time. But no promises :)
