### ISSUE TITLE
no-network icon misleading

### ISSUE THREAD

**Issue by jomo** [alterstep/dnscrypt-osxclient#51]
I think the ![active](https://raw.githubusercontent.com/alterstep/dnscrypt-osxclient/4d2c1e80b6cfbbe4c4338ba4b30e6eac522e21b6/DNSCrypt-Menubar/DNSCrypt-Menubar/icon-dnscrypt-active.png "active") and ![inactive](https://raw.githubusercontent.com/alterstep/dnscrypt-osxclient/4d2c1e80b6cfbbe4c4338ba4b30e6eac522e21b6/DNSCrypt-Menubar/DNSCrypt-Menubar/icon-dnscrypt-inactive.png "inactive") icons are well understandable, but the "no-network" icon ![no-network](https://raw.githubusercontent.com/alterstep/dnscrypt-osxclient/4d2c1e80b6cfbbe4c4338ba4b30e6eac522e21b6/DNSCrypt-Menubar/DNSCrypt-Menubar/icon-no-network.png "no-network") doesn't really suggest there's an issue.

In fact, I was wondering what it meant and only found out via the file name in this repo.

The text "Standby" also doesn't really tell me what the problem is:
![standby screenshot](https://i.imgur.com/hoejMYG.png)

----

Maybe you could put a red exclamation mark in place of the padlock?

**Comment by alterstep** [comment]
How about dots (...) ?

**Comment by jomo** [comment]
I noticed the inkscape file has a layer called `Reference no network` showing a thinner border and a cross in the center. I made a version that looks like the reference:

![no network](https://i.imgur.com/9jBsJbo.png "no network") | The inkscape source is [here](http://chunk.io/f/3d145d97f29c4341be105472b75bc434).

That icon would work great IMO.

**Comment by alterstep** [comment]
The icon was changed according to your suggestion. And you are correct, it is less misleading.
The next version will have it. Thank you!
