### ISSUE TITLE
bypass using wrong resolver (default gateway?)

### ISSUE THREAD

**Issue by jomo** [alterstep/dnscrypt-osxclient#52]
With dnscrypt disabled, my name servers are:
```
nameserver 192.168.8.5
nameserver 192.168.8.8
nameserver 192.168.8.9
```

When I put `example.com` in the bypassing rules, it creates a file at `/etc/resolver/example.com`:
```
# automatically generated by the dnscrypt user interface
nameserver 192.168.8.254
```

using `ping example.com` also results in DNS queries being sent to 192.168.8.254, but it doesn't answer since it's not a DNS server.

From the docs:
> Domains listed here will bypass DNSCrypt in order to be sent to the **default resolvers**.

That doesn't seem to be the case.

I inspected the DHCP packets, and `192.168.8.254` is the `Default-Gateway` field, not the `Domain-Name-Server` field. These may be the same on many networks, especially on home routers, but in this case it's not.

------

*btw, I can't press enter to insert a newline in the bypassing field, or any field in the 'Advanced' tab. Pasting does work, however*

**Comment by jomo** [comment]
I found the cause. [The command](https://github.com/alterstep/dnscrypt-osxclient/blob/0848088f2206f8638ea32437066a4666276e6ddd/DNSCrypt-Preference-Pane/DNSCrypt/extra/usr/scripts/get-dhcp-resolvers.sh#L5-L6)
```shell
ifconfig -a | awk '/^[^ :]*:/ { sub(/:.*$/,empty); iface=$0 } /status: active/ { print iface }'
```
doesn't return anything. This causes the script to fallback to the gateway.

**Comment by jomo** [comment]
nvm that, it actually does work, but the tab went missing when I pasted it into my terminal.

**Comment by alterstep** [comment]
Yes, it assumes that the DNS resolvers come from the DHCP server instead of being static.

But wait! Everything is not lost!

In the "Advanced" tab, there is a form titled "When not using DNSCrypt, use the following static DNS resolvers". Which is exactly for your case: static resolvers!

**Comment by jomo** [comment]
The DHCP server *does* send the resolvers, but DNSCrypt doesn't use them for some reason.
And the resolvers are *not static*.

Sorry if my last comment was confusing. The command I posted above *does* work, the initial issue isn't fixed. Can you re-open?

**Comment by jomo** [comment]
This is still an issue, I _literally_ copy the DHCP-issued resolvers 
```shell
ipconfig getpacket en1 | grep domain_name_server
```
and paste them into the field that says 'leave blank for DHCP'.

Leaving it blank does not seem to work, as explained above.
Can you re-open, please?
