### ISSUE TITLE
minisign-verify cannot be opened due to a problem

### ISSUE THREAD

**Issue by D1001** [alterstep/dnscrypt-osxclient#53]
Using DNSCrypt 1.0.8 on MacOS X 10.10.4

Process:               minisign-verify [1049]
Path:                  /Library/PreferencePanes/DNSCrypt.prefPane/Contents/Resources/usr/bin/minisign-verify
Identifier:            minisign-verify
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        sh [1014]
Responsible:           DNSCrypt Menubar [665]
User ID:               501

Date/Time:             2015-07-12 05:02:15.072 -0400
OS Version:            Mac OS X 10.10.4 (14E46)
Report Version:        11
Anonymous UUID:        F12B45EC-2CA8-AC74-DDF6-3FE7B9CE847B

Time Awake Since Boot: 130 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/lib/libsodium.13.dylib
  Referenced from: /Library/PreferencePanes/DNSCrypt.prefPane/Contents/Resources/usr/bin/minisign-verify
  Reason: image not found

Binary Images:
    0x7fff6b848000 -     0x7fff6b87e837  dyld (353.2.1) <72A99D0F-0B56-3938-ABC5-67A0F33757C4> /usr/lib/dyld

Model: MacBookPro6,2, BootROM MBP61.0057.B0F, 2 processors, Intel Core i5, 2.53 GHz, 8 GB, SMC 1.58f17
Graphics: Intel HD Graphics, Intel HD Graphics, Built-In
Graphics: NVIDIA GeForce GT 330M, NVIDIA GeForce GT 330M, PCIe, 256 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1067 MHz, 0x80CE, 0x4D34373142353237334348302D4346382020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1067 MHz, 0x80CE, 0x4D34373142353237334348302D4346382020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x93), Broadcom BCM43xx 1.0 (5.106.98.100.24)
Bluetooth: Version 4.3.5f8 15969, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: ST750LX003-1AC154, 750.16 GB
Serial ATA Device: MATSHITADVD-R   UJ-898
Thunderbolt Bus:

**Comment by alterstep** [comment]
I am really sorry :-1: 

The file `libsodium.13.dylib` is required and I have it installed system-wide, but I forgot to include what it takes to have it in the package.

I uploaded a new version, 1.0.9, to fix it. Unfortunately you have to download it manually because this is affecting the self-update system.
