### ISSUE TITLE
On Mac - Few glitches

### ISSUE THREAD

**Issue by TraderStf** [alterstep/dnscrypt-osxclient#54]
Hello,

The preferences has cmd-, (comma) as a shortcut, but it useless as it does not works.
I think because most apps use already this shortcut.
Even if the front app does not use it, it does not open the prefs.
(probably same for cmd-E and H)

In the About, concerning Little Snitch, I think this one is missing:
Allow outgoing TCP connections on port 80 $(http) of updates.dnscrypt.org for system process (curl)

The $ here is to highlight a little typo in line 4, it is 80( http) instead of 80 (http)

A friend asked me if there is any reason to choose one or another DNSCrypt server, safer, faster (I suppose closer is better), reliable/up-time, privacy?

If you need help, I am here.

Thanks a lot,

**Comment by alterstep** [comment]
Hello!

These glitches have been fixed, thank you!

cmd-comma works for me. I tried on a German and on a US keyboard and it worked, but you need to pull down the menu first. I am wondering if the problem is that it doesn't work with some keyboards.
What keyboard do you have? Do you need to press a special key such as Shift to enter a coma?

**Comment by TraderStf** [comment]
Hi,
No, it works in all apps, cmd and comma. (Belgian=French Keyboard)
Same with cmd-E or H.
If the menu must be down/visible, yes the shortcuts are working.

Some other tools in the menu bar can have shortcuts working without having the menu down. I don't know if they are useful anyway, for me it is ok.

They can be removed, if someone wants shortcuts, he can use Apple - Sys Pref - Keyboard - Shortcuts to define his own.
So no more complain for you :-)
Hummm I just tried but does not seems to get updated, new 'user' shortcuts are not visible or working.

**Comment by TraderStf** [comment]
In fact, the user shortcut appears after a hide/relaunch, but here too, only work if menu is down...
No matter the combination ctrl-cmd-option-keys, always same reaction.
(BTW is it a hide or quit?)

**Comment by TraderStf** [comment]
I did not RTFM... so forgive me :-) and while I am here, few wishes.

What could be helpful would be to explain:

- best to use a closer DNSC server for speed, can find it based on IP block, free DB available with countries blocks

- best to use this server because... I don't know what.... are they all the same, safety, reliable...

- best to use DNS not from your ISP in the field 'when not using...' to enhance privacy, use google, opendns, ultradns, hurricane Electric, dnsbycomodo, norton... could perhaps include a small popup with DNS of these big guys.

- could this still be useful, https://code.google.com/p/namebench/
With just DNSC ones.

- is this solved with DNSC, 
https://dnsleaktest.com/
http://blog.cyberghostvpn.com IP6 Leakage


Suggestions:
- Move menu "client ui version" inside the prefs.
- Show local/remote IP in dialog/menu
- Use the beautiful green shield icon in the dialog also in the menu bar. Keep a black one for Apple new black sad mode...

It is perhaps out of the goal of DNSC, but as it is at a low-level, perhaps can add features, like:
- connect to domains X only if IP is ###, vpn...
- block all net exchanges if vpn is down (kill switch)
- show if vpn is on or not

You get the idea, provide feedback and control for less techies.

Thanks for your nice work!


FYI, don't know if can be of any interest.
http://superuser.com/questions/811632/prevent-outgoing-traffic-unless-openvpn-connection-is-active-using-pf-conf-on-ma?rq=1

http://superuser.com/questions/577094/how-can-i-tell-if-os-x-is-connected-to-a-vpn-network-from-the-command-line

http://apple.stackexchange.com/questions/46876/how-to-only-route-office-traffic-over-the-vpn-while-having-default-route-for-oth
Switch only in PPTP, not IPSEC...

http://www.sparklabs.com/support/preventing_network_and_dns_traffic_leaks/

http://www.ugdsoft.com/products/vpnwatcher/

http://www.vpntracker.com/us/techdetails.html

**Comment by ajkblue** [comment]
@TraderStf as a longtime user of the DNSCrypt OS X Client, let my try to answer some of your questions and throw in my two cents on some of your suggestions:

Explanations
- You'll find that many servers on the DNSCrypt list are part of the [OpenNIC Project](https://www.opennicproject.org) which had many advantages over regular DNS servers, shown on their webpage. Generally, closer servers are faster.
- You can compare the list that [OpenNIC](https://www.opennicproject.org) will provide as the closest to the full resolvers list that DNSCrypt uses [here](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv), although not all are part of this list, many are. Of course, you can always use Google's or OpenDNS, but I suggest that you specifically check their privacy policies.
- In the "When not using DNSCrypt" box in the preferences, you can easily enter any DNS Server that you want right there, e.g. Google is 8.8.8.8 and 8.8.4.4. It's better to not limit server options.
- [NameBench](https://code.google.com/p/namebench/) is simply used to find out what DNS servers are fastest for you. You can manually enter the IP address of servers you want to test or let the application run speed tests on the major providers (Google, OpenDNS, etc...) there is also on option in the application to check the speed of other local dns servers.
- Yes, DNSCrypt does prevent you from DNS leak (not sure about IPv6, I can't test it).
- DNSSEC doesn't really provide the security that you may think it does, if your of the technical sort, see this: http://sockpuppet.org/blog/2015/01/15/against-dnssec/

Suggestions:
I find it useful to be able to check which version I am running quickly from the menu bar. But I find the rest of your suggestions beyond the scope of what the DNSCrypt Client is here to achieve. If you need to know your local IP address just option click on the Wi-Fi icon in the menu bar. Your public IP address can be found simply by looking up "What's my IP?" in any search engine. Personally, I like the option of being able to have a simple black and white mode for the menu bar icon so it's less distracting. The current icon is just fine the way it is now - I've never had to glance at it twice to make sure I'm connected. DNSCrypt's goal is not to be a vpn client with a kill switch, but if you use OS X's built in VPN there is an option to show connection status in the menu bar and show the connection time. Maybe an app such as [ControlPlane](http://www.controlplaneapp.com) may help you with the more advanced network capabilities.

I would prefer that the client be kept simple and speedy.
Also when you select "Hide from menu bar" in the client, that's really what happens, just the icon is hidden. DNSCrypt is still running in the background protecting you.

**Comment by TraderStf** [comment]
@ajkblue thanks a lot for your answers, they are very interesting.

My goal is to make things simpler for less techies, having clear explanations and easy settings without having to jump everywhere or to add dozen of utilities.

Namebench is really a great tool, worth a try as speed differences can be so huge.

For IP6, may be this is the answer, but that's out of the scope of this thread, sorry for that.
https://www.ipredator.se/guide/pptp/lion#configuration on step 8.
