### ISSUE TITLE
Can launch several times DNSC Menubar app

### ISSUE THREAD

**Issue by TraderStf** [alterstep/dnscrypt-osxclient#55]
Can launch several times the DNSCrypt menubar application (v1.09).
Several icons in the menu bar.

**Comment by alterstep** [comment]
Sure, if you start the application yourself, but is that a problem?

The menubar app is normally started by launchd after a reboot, and it only starts one instance.

I can add some kind of locking mechanism to prevent users from manually starting it, but I don't think it is worth it. And you can impress you friends by running many of them!
