### ISSUE TITLE
3 tiff icons are 17x17 and 34x34?

### ISSUE THREAD

**Issue by TraderStf** [alterstep/dnscrypt-osxclient#56]
Is it normal the 3 tiff icons have a size of 17x17 and 34x34 pixels?

Can perhaps help, produce lots of sizes in one shot.
http://realfavicongenerator.net/

**Comment by TraderStf** [comment]
About icons, I have check some new apps, they have the following pixels^2 and dpi.

01. 1024-144
02. 512-72
03. 512-144
04. 256-72
05. 256-144
06. 128-72
07. 64-44
08. 32-72
09. 32-144
10. 16-72

**Comment by alterstep** [comment]
These are the menu icons. 17x17 is the size for non-retina displays, and 34x34 is the size for retina displays. 
This is required for native OSX applications and it is completely different from the icons for web browsers.
