### ISSUE TITLE
Problem resolving AAAA records over an IPV4 connection

### ISSUE THREAD

**Issue by simonclausen** [alterstep/dnscrypt-osxclient#57]
Hi,

I was approached by a user of dnscrypt.eu, who raised a concern about not being able to resolve AAAA records over IPV4. A little testing indicates that it is his use of dnscrypt-osxclient that causes the issue.

I have been able to replicate this using various dnscrypt providers, using version 1.0.0 and 1.0.9 of dnscrypt-osxclient.

Example:

```
dig google.com AAAA

; <<>> DiG 9.8.3-P1 <<>> google.com AAAA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35918
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1252
;; QUESTION SECTION:
;google.com.			IN	AAAA

;; Query time: 1 msec
;; SERVER: 127.0.0.54#53(127.0.0.54)
;; WHEN: Sun Jul 19 15:51:33 2015
;; MSG SIZE  rcvd: 39
```

**Comment by jomo** [comment]
> a user of dnscrypt.eu

Hi there! :sunglasses: 

In my case, dnscrypt is started by osxclient via:
```shell
dnscrypt-proxy \
  --resolver-name=dnscrypt.eu-nl \
  --local-address=127.0.0.54 \
  --resolver-name=dnscrypt.eu-nl \
  --ephemeral-keys \
  --pidfile=/var/run/dnscrypt-proxy.pid \
  --user=daemon \
  --daemonize \
  --plugin=libdcplugin_example_logging.la
```

```shell
$ dig @127.0.0.54 google.com AAAA

; <<>> DiG 9.8.3-P1 <<>> @127.0.0.54 google.com AAAA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32839
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1252
;; QUESTION SECTION:
;google.com.			IN	AAAA

;; Query time: 2 msec
;; SERVER: 127.0.0.54#53(127.0.0.54)
;; WHEN: Sun Jul 19 16:23:37 2015
;; MSG SIZE  rcvd: 39

```

Other commands are (obviously) also failing:
```shell
$ ping6 google.com
ping6: getaddrinfo -- nodename nor servname provided, or not known
```

Oddly though, it seems to be working after switching to an IPv6 resolver and back to the IPv4 resolver:
```shell
$ dig @127.0.0.54 google.com AAAA

; <<>> DiG 9.8.3-P1 <<>> @127.0.0.54 google.com AAAA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23941
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	AAAA

;; ANSWER SECTION:
google.com.		32	IN	AAAA	2607:f8b0:4001:c02::64

;; AUTHORITY SECTION:
google.com.		171624	IN	NS	ns2.google.com.
google.com.		171624	IN	NS	ns1.google.com.
google.com.		171624	IN	NS	ns3.google.com.
google.com.		171624	IN	NS	ns4.google.com.

;; ADDITIONAL SECTION:
ns1.google.com.		171624	IN	A	216.239.32.10
ns2.google.com.		171624	IN	A	216.239.34.10
ns3.google.com.		171624	IN	A	216.239.36.10
ns4.google.com.		171624	IN	A	216.239.38.10

;; Query time: 32 msec
;; SERVER: 127.0.0.54#53(127.0.0.54)
;; WHEN: Sun Jul 19 16:19:43 2015
;; MSG SIZE  rcvd: 203

```

I can reproduce this by turning off WiFi and disabling DNSClient, and then enable both again.
Requests are then no longer working. After switching to the v6 resolver and back to the v4 resolver, everything is fine again.

I used `tcpdump` to check if requests are sent to the IPv4 resolver, which was not the case until switching forth and back:
```shell
$ tcpdump -i en1 -vvv host 176.56.237.171
16:30:43.324488 IP (tos 0x0, ttl 64, id 24748, offset 0, flags [none], proto UDP (17), length 540)
    192.168.0.17.57085 > resolver1.dnscrypt.eu.https: [udp sum ok] UDP, length 512
16:30:43.350984 IP (tos 0x0, ttl 48, id 14441, offset 0, flags [none], proto UDP (17), length 460)
    resolver1.dnscrypt.eu.https > 192.168.0.17.57085: [udp sum ok] UDP, length 432
```

**Comment by alterstep** [comment]
Thank you guys for contacting me about this!

There is an explanation, and this behaviour is not due to anything wrong with dnscrypt.eu which is a great service.

OSXClient does a few things under the hood to improve the user experience. One thing it does when the network configuration changes is to check that the host can route IPv6 packets.

If there is IPv6 connectivity, AAAA records are returned as expected.

It may not be the case on Linux and Windows but OSX likes the always send AAAA + A queries for everything, even when there is no IPv6 connectivity. Web browsers send AAAA queries for every domain and wait for them even if they will never be able to connect to the resulting address.

So if there is no IPv6 connectivity, or if it doesn't work, OSX client skips IPv6-only resolvers, and turns on the libdcplugin_example_ldns_aaaa_blocking plugin (included with dnscrypt-proxy).

What this plugin does is that when a AAAA query is received, the proxy directly respond to the client that there is are no IPv6 records, instead of asking the resolver, waiting for a response, and forwarding it even if the IPv6 address cannot be used.

This halves the number of queries waiting for a response. I have fast DSL now but In the city I was previously living, I had a satellite connection, and enabling this plugin made a massive difference.

If the box has IPv6 connectivity, without any firewalls blocking IPv6 traffic, and OSXClient doesn't correctly detect it and return AAAA records, there is a bug in my client. And it can totally be the case!

If returning AAAA records even when IPv6 doesn't work is something that people need, I can add a switch to never enable the aaaa_blocking plugin. But provided that IPv6 detection works as expected, it is often useful.

**Comment by jomo** [comment]
I don't know if there are applications that expect AAAA to be always returned / dns queries to not be tampered with, but I definitely have working IPv6 and [`ping6 -c 1 2620:0:ccc::2`](https://github.com/alterstep/dnscrypt-osxclient/blob/4d2c1e80b6cfbbe4c4338ba4b30e6eac522e21b6/DNSCrypt-Preference-Pane/DNSCrypt/extra/usr/scripts/start-dnscrypt-proxy.sh#L77-L87) is working, too.

 I'll try to find out more.

**Comment by alterstep** [comment]
What you can do is turn on debugging:

    touch '/Library/Application\ Support/DNSCrypt/control/debug.enabled'

A log file "/var/log/dnscrypt-osxclient-debug.log" will be created and should tell you the outcome of the ipv6 detection - but you already figured out how it was done!

**Comment by jomo** [comment]
I found that, but for some reason the log file is not created. There's only `dnscrypt-query.log`, even after turning osxclient off and on again.

**Comment by alterstep** [comment]
Double check the file name? I know this is a very stupid statement, but I can't imagine why you wouldn't get logs if the debug.enabled file is here.

**Comment by jomo** [comment]
Turns out I was stupid :shit:

Anyway, the problem seems to occur when DNSClient is running with WiFi off, and *then* WiFi is turned on. I assume IPv6 isn't immediately available and thus yourIPv6 check is failing.
It did work when I first turned on WiFi and *then* turned on DNSClient.

Here's the full debug log + some comments:
```yml
# Turned off DNSClient
Sun Jul 19 21:47:09 CEST 2015 - DNSCrypt-OSXClient configuration changed
Sun Jul 19 21:47:09 CEST 2015 - Stopping dnscrypt-proxy
Sun Jul 19 21:47:09 CEST 2015 - Trying to stop dnscrypt-proxy by killing pid [39049]
Sun Jul 19 21:47:09 CEST 2015 - Changing the DNS configuration to use the default DNS resolvers
Sun Jul 19 21:47:10 CEST 2015 - Flushing the local DNS cache
# Turned off WiFi
# Turned on WiFi
# Turned on DNSClient
Sun Jul 19 21:47:48 CEST 2015 - DNSCrypt-OSXClient configuration changed
Sun Jul 19 21:47:48 CEST 2015 - DNSCrypt has been requested
Sun Jul 19 21:47:48 CEST 2015 - Changing the DNS configuration to use the default DNS resolvers
Sun Jul 19 21:47:48 CEST 2015 - Flushing the local DNS cache
Sun Jul 19 21:47:48 CEST 2015 - Switching to dnscrypt if required (pause=0)
Sun Jul 19 21:47:48 CEST 2015 - Checking if the router hijacks HTTP queries
Sun Jul 19 21:47:48 CEST 2015 - The router doesn't hijack HTTP queries
Sun Jul 19 21:47:49 CEST 2015 - dnscrypt-proxy should be (re)started, stopping previous instance if needed
Sun Jul 19 21:47:49 CEST 2015 - Stopping dnscrypt-proxy
Sun Jul 19 21:47:49 CEST 2015 - Testing IPv6 connectivity
Sun Jul 19 21:47:49 CEST 2015 - IPv6 connectivity detected
Sun Jul 19 21:47:49 CEST 2015 - Running a test dnscrypt proxy for [dnscrypt.eu-nl using DNSCrypt over TCP]
Sun Jul 19 21:47:49 CEST 2015 - Proxy for [dnscrypt.eu-nl using DNSCrypt over TCP] is up
Sun Jul 19 21:47:49 CEST 2015 - Proxy for [dnscrypt.eu-nl using DNSCrypt over TCP] can be used
Sun Jul 19 21:47:50 CEST 2015 - Running a test dnscrypt proxy for [dnscrypt.eu-nl using DNSCrypt over UDP]
Sun Jul 19 21:47:50 CEST 2015 - Proxy for [dnscrypt.eu-nl using DNSCrypt over UDP] is up
Sun Jul 19 21:47:50 CEST 2015 - Proxy for [dnscrypt.eu-nl using DNSCrypt over UDP] can be used
Sun Jul 19 21:47:50 CEST 2015 - Plugins to be used: [ --plugin=libdcplugin_example_logging.la,/var/log/dnscrypt-query.log]
Sun Jul 19 21:47:50 CEST 2015 - Starting dnscrypt-proxy --resolver-name=dnscrypt.eu-nl
Sun Jul 19 21:47:51 CEST 2015 - Checking if the current configuration hijacks all DNS queries
Sun Jul 19 21:47:51 CEST 2015 - Current configuration doesn't seem to hijack all DNS queries
Sun Jul 19 21:47:51 CEST 2015 - Setting DNS resolvers to [127.0.0.54]
Sun Jul 19 21:47:52 CEST 2015 - Flushing local DNS cache
# Everything works
# Turned off WiFi
# Turned off DNSClient
Sun Jul 19 21:48:30 CEST 2015 - DNSCrypt-OSXClient configuration changed
Sun Jul 19 21:48:31 CEST 2015 - Stopping dnscrypt-proxy
Sun Jul 19 21:48:31 CEST 2015 - Trying to stop dnscrypt-proxy by killing pid [39784]
Sun Jul 19 21:48:31 CEST 2015 - Changing the DNS configuration to use the default DNS resolvers
Sun Jul 19 21:48:31 CEST 2015 - Flushing the local DNS cache
# Turned on DNSClient (WiFi still off)
Sun Jul 19 21:48:39 CEST 2015 - DNSCrypt-OSXClient configuration changed
Sun Jul 19 21:48:39 CEST 2015 - DNSCrypt has been requested
Sun Jul 19 21:48:39 CEST 2015 - Changing the DNS configuration to use the default DNS resolvers
Sun Jul 19 21:48:39 CEST 2015 - Flushing the local DNS cache
Sun Jul 19 21:48:39 CEST 2015 - Switching to dnscrypt if required (pause=0)
Sun Jul 19 21:48:40 CEST 2015 - Checking if the router hijacks HTTP queries
Sun Jul 19 21:48:50 CEST 2015 - The router hijacks HTTP queries - DNSCrypt is likely to be blocked
Sun Jul 19 21:48:50 CEST 2015 - Switching to dnscrypt if required (pause=0.1)
Sun Jul 19 21:48:50 CEST 2015 - Checking if the router hijacks HTTP queries
Sun Jul 19 21:49:00 CEST 2015 - The router hijacks HTTP queries - DNSCrypt is likely to be blocked
Sun Jul 19 21:49:00 CEST 2015 - Switching to dnscrypt if required (pause=0.2)
# Turned on WiFi
Sun Jul 19 21:49:00 CEST 2015 - Checking if the router hijacks HTTP queries
Sun Jul 19 21:49:02 CEST 2015 - The router doesn't hijack HTTP queries
Sun Jul 19 21:49:02 CEST 2015 - dnscrypt-proxy should be (re)started, stopping previous instance if needed
Sun Jul 19 21:49:02 CEST 2015 - Stopping dnscrypt-proxy
Sun Jul 19 21:49:02 CEST 2015 - Testing IPv6 connectivity
Sun Jul 19 21:49:02 CEST 2015 - IPv6 connectivity is not available
Sun Jul 19 21:49:02 CEST 2015 - Running a test dnscrypt proxy for [dnscrypt.eu-nl using DNSCrypt over TCP]
Sun Jul 19 21:49:02 CEST 2015 - Proxy for [dnscrypt.eu-nl using DNSCrypt over TCP] is up
Sun Jul 19 21:49:02 CEST 2015 - Proxy for [dnscrypt.eu-nl using DNSCrypt over TCP] can be used
Sun Jul 19 21:49:03 CEST 2015 - Running a test dnscrypt proxy for [dnscrypt.eu-nl using DNSCrypt over UDP]
Sun Jul 19 21:49:03 CEST 2015 - Proxy for [dnscrypt.eu-nl using DNSCrypt over UDP] is up
Sun Jul 19 21:49:03 CEST 2015 - Proxy for [dnscrypt.eu-nl using DNSCrypt over UDP] can be used
Sun Jul 19 21:49:03 CEST 2015 - Plugins to be used: [ --plugin=libdcplugin_example_logging.la,/var/log/dnscrypt-query.log]
Sun Jul 19 21:49:03 CEST 2015 - Starting dnscrypt-proxy --resolver-name=dnscrypt.eu-nl
Sun Jul 19 21:49:04 CEST 2015 - Checking if the current configuration hijacks all DNS queries
Sun Jul 19 21:49:04 CEST 2015 - Current configuration doesn't seem to hijack all DNS queries
Sun Jul 19 21:49:04 CEST 2015 - Setting DNS resolvers to [127.0.0.54]
Sun Jul 19 21:49:05 CEST 2015 - Flushing local DNS cache
# AAAA queries not working
```

**Comment by alterstep** [comment]
Interesting and unexpected behaviour! IPv4 and IPv6 not coming up and the same time, even if there is only one network configuration change event.

Constantly polling for changes is not a good idea - constantly polling is never a good idea.
Waiting after a change is not a good idea - users want to wait less, not more.

Can you think of a way to work around this?

We can add a button to explicitly enable or disable this feature. Maybe call it "if you don't have IPv6, check this box to reduce latency". So it won't be automatic any more. But if we can find a work around to keep it automatic, it would be better!

**Comment by alterstep** [comment]
This is what I ended up doing. The checkbox is off by default. This is going to be in the next release.

![screen shot 2015-07-28 at 12 14 28 am](https://cloud.githubusercontent.com/assets/7305239/8919204/bf9caf34-34bd-11e5-93bf-8850df9dce0c.png)

**Comment by jomo** [comment]
:+1:
