### ISSUE TITLE
Shouldn't application updates & resolver list updates be over https?

### ISSUE THREAD

**Issue by ajkblue** [alterstep/dnscrypt-osxclient#63]
While looking through the source I noticed that the path specified for downloading application updates and the resolver list are not over https. Shouldn't the [commin.inc](https://github.com/alterstep/dnscrypt-osxclient/blob/a9d852b76dc02e97e20dcb60f1ccaf6dd22b8aad/DNSCrypt-Preference-Pane/DNSCrypt/extra/usr/scripts/common.inc) file specify downloading those over https instead of plain http? I also noticed that when visiting https://updates.dnscrypt.org my browser throws a ssl error (certificate mismatch), so if downloading over https the certificate error should be fixed first.

**Comment by alterstep** [comment]
It doesn't have to use https!

The content of these files is public so there is nothing to hide.

Before replacing a previous version, a new file is always verified using a PGP-like digital signature. This provides more security than https.

The script doing resolvers list updates is here: https://github.com/alterstep/dnscrypt-osxclient/blob/master/DNSCrypt-Preference-Pane/DNSCrypt/extra/usr/scripts/update-resolvers-list.sh

As you can see, it calls minisign-verify to check the signature. If the signature is not valid, it doesn't go any further.

Application updates are made by that script: https://github.com/alterstep/dnscrypt-osxclient/blob/master/DNSCrypt-Preference-Pane/DNSCrypt/extra/usr/scripts/update-dnscrypt-app.sh

Same thing: if the signature is not valid, the file is deleted.

**Comment by ajkblue** [comment]
I didn't realize that the client uses such high-security measures. A signature file is a very good way to verify the resolvers and application. Bravo for keeping security top-notch!
