### ISSUE TITLE
Prevent plain-text query leakage

### ISSUE THREAD

**Issue by iangelov** [alterstep/dnscrypt-osxclient#64]
Hello guys,

I'm wondering whether there's a way to not leak DNS queries while reconfiguring dnscrypt-proxy (like changing nameservers).

Currently while this happens some queries leak to the DNS server/s configured to serve as default on the system (in other words - when you're not running the proxy). I'm fairly certain that this is not caused by the application itself and stems from the way networking on Mac OS X works, but I'm wondering whether a solution could be found to prevent this from happening at this layer (and not have to fiddle around pf, etc, since not everyone is capable of doing that).

How to reproduce - tcpdump traffic sent to port 53 and not to the default dnscrypt-proxy IP.

**Comment by ajkblue** [comment]
This leakage also happens on boot up, before the dnscrypt client application has started and connected to a server. It would be nice to have an option to block all other DNS traffic when the Dnscrypt client hasn't yet connected.

**Comment by alterstep** [comment]
Block port 53 on the router. DNSCrypt doesn't use port 53, so it will prevent any form of traditional DNS leakage.

There is always a hard balance to find between security and usability. Suppose port 53 is blocked directly on your laptop. If you close your laptop, and reopen it in a place where DNSCrypt is blocked, you will be left with a computer that doesn't work any more. It's not just about DNS, it may even prevent the Wifi to connect. I prefer not to try to go that way, or else a lot of people may complain.

**Comment by alterstep** [comment]
A different way, maybe, is to configure bogus DNS resolver IPs on the router, such as an internal network IP.
Even if the computer sends a query without DNSCrypt, the router will not forward it anywhere.
