### ISSUE TITLE
Fail to handle Network configuration changes

### ISSUE THREAD

**Issue by Fl0p** [alterstep/dnscrypt-osxclient#70]
I don't know why but i newer saw  "Network configuration changed" in log
so check-network-change.sh is never called
so in DNSCrypt/states/dhcp-dns i always have same old DNS  wich is wrong
And when i use bypass i have wrong configuration in /etc/resolver/

After some research i released the problem in handle-network-change.sh
```sh
if [ x"$1" != 'x--boot' ]; then
  [ ! -e "$FALLBACK_FILE" ] && exit 0
  ./check-network-change.sh || exit 0
fi
```
It will newer ./check-network-change.sh without fallback
Is it correct behaviour?
In last UI version i have no checkbox to switch falback on
may be better to change this to lines

```sh
if [ x"$1" != 'x--boot' ]; then
  ./check-network-change.sh || exit 0
  [ ! -e "$FALLBACK_FILE" ] && exit 0
fi
```
How do You think?

**Comment by Fl0p** [comment]
Also what the purposes of FALLBACK_FILE ?
How i can enduser configure it?

**Comment by alterstep** [comment]
Hi

This is the correct behaviour. Without fallback, we should never change the resolver.

Fallback is "Automatically disable if blocked" in the UI.
