### ISSUE TITLE
Need to delete firewall authorization to make it work

### ISSUE THREAD

**Issue by TraderStf** [alterstep/dnscrypt-osxclient#71]
I have deleted DNSC (v.10) few weeks ago.
Today I reinstall it, impossible to connect.
Network, reboot, littlesnitch,... no matter what, never connect to any DNSC server.
Then I delete all "low level" firewall authorizations (dig, bootp,... dnscrypt).
After that, I had to add a new DNS in Network panel to make internet works.
Then enable DNSC, and now it works.

**Comment by alterstep** [comment]
It doesn't do anything with firewall rules, antivirus or little snitch.
It doesn't read the configuration of any of these, it doesn't change settings of any of these, and I don't think any applications should ever do that except malware.
If you deinstalled dnscrypt and reinstalled it, your firewall didn't understand that it was the same software. Permissions on system commands such as "dig" were maybe still allowed, but applications installed by dnscrypt-osxclient weren't.
There is nothing that can be done by dnscrypt-osxclient to avoid that.
