### ISSUE TITLE
El Capitan 10.11.1 latest beta

### ISSUE THREAD

**Issue by ryapeter** [alterstep/dnscrypt-osxclient#74]
Resolver won't work. Let me know if you need anything.

**Comment by alterstep** [comment]
I am using this version and have no troubles with it.
It may sound like a cliche, but did you try uninstalling and reinstalling OSX Client?

**Comment by ryapeter** [comment]
Hi,

Just check my laptop after reading your message and it suddenly work. Last night I tried to turn it on and off and It won't work at all.

Case Closed thanks.
