### ISSUE TITLE
Presence of active .tcshrc renders DNSCrypt useless in Mac OS X Yosemite 10.10.5 

### ISSUE THREAD

**Issue by justPaulo** [alterstep/dnscrypt-osxclient#75]
https://github.com/jedisct1/dnscrypt-proxy/issues/291#issuecomment-143652951

**Comment by alterstep** [comment]
The -f switch was not included so the user .tcshrc was read. The switch was added.

**Comment by justPaulo** [comment]
Is that inclusion present in scrypt-osxclient-1.0.10.dmg ? It seems to be from 23rd of July.

**Comment by alterstep** [comment]
It is in the code in git, but it's not in the dmg. It will be when a new version will be released!

**Comment by justPaulo** [comment]
Ok, got it.
res = [self fromCommand: @"/bin/csh" withArguments: [NSArray arrayWithObjects: @"-f", @"-c", @"cd '" kDNSCRYPT_SCRIPTS_BASE_DIR @"' && exec ./get-dnscrypt-status.sh", nil]];
