### ISSUE TITLE
Not usable in OS X El Capitan

### ISSUE THREAD

**Issue by jomo** [alterstep/dnscrypt-osxclient#76]
I can't make any changes, that includes disabling DNSCrypt.

I assume this is caused by Apple's new *System Integrity Protection* "rootless", in particular the [File System Protections](https://developer.apple.com/library/prerelease/mac/documentation/Security/Conceptual/System_Integrity_Protection_Guide/FileSystemProtections/FileSystemProtections.html) which prevents (with a few exceptions) to write to:

- /bin
- /sbin
- /usr
- /System
- /Applications/Utilities

----

A work-around to disable DNSCrypt is to remove `127.0.0.x` from OS X' DNS settings.

**Comment by jomo** [comment]
I had issues with homebrew and ran
```shell
sudo chown -R $(whoami):admin /usr/local
```
to fix them. I guess that also fixed this issue. 

Can someone confirm?

**Comment by ding444** [comment]
@jomo Negative.  Doing so did not fix it for me

**Comment by jomo** [comment]
The only other change I made that I can think of right now is a reboot. Did you try that after the `chown`?

**Comment by ding444** [comment]
I hadn't tried rebooting, but I just did and after rebooting it still doesn't work.

**Comment by ding444** [comment]
Update: I reinstalled it on a whim and it's working after install and reboot.  I performed the El Capitan upgrade and not a clean install so maybe there's something associated with that that disables it.

**Comment by jedisct1** [comment]
As pointed out by Jomo, it's very likely to be due to SIP.

If `/usr/local` already exists, all is fine. If it doesn't exist, it cannot be created any more.
This breaks Homebrew for the same reason.

Link + how to fix it:
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md

OSXClient requires plugins to be `/usr/local` and to be owned by `root`. If you issue `sudo chown -R $(whoami):admin /usr/local`, this will downgrade ownership of the files with these plugins to the user account, so it will not work any more. But if you reinstall the package afterwards, the files will get the right permissions.

Maybe one way to fix this is to move the dnscrypt proxy and the plugins to `/Library/PreferencePanes`? That's pretty ugly, but it might work.

**Comment by Pmavrovic** [comment]
Also noticed similar issues.
Also have ongoing issue with very slow shutdown times as compared to removing DNScrypt.

To test I would kill all DNScrypt services and then would have 5 - 8 second shutdown times..
Once I would re-enable DNScrypt I had up to 2 - 3 minute shutdown times.

**Comment by jomo** [comment]
Thanks @jedisct1. I had some weird issues with DNSCrypt claiming my network would be hijacking queries (on _some_ networks, _sometimes_).

This fixed it:
```shell
sudo chown -R root:wheel /usr/local/{lib/dnscrypt-proxy,sbin/dnscrypt-proxy}
```

**Comment by hubdotcom** [comment]
Working fine on El Captain with SIP enabled running dnscrypt  v1.0.10

**Comment by Pmavrovic** [comment]
Do you see any shutdown delays?

I see about 30 seconds to 2 mins extra delay on shutdowns with it is installed




Kind Regards,

		Paul Mavrovic

**Comment by ysupr** [comment]
so it really solved now? 
or still with some side effect like what @Pmavrovic said?

**Comment by ajkblue** [comment]
@ysupr I've previously opened a separate issue, https://github.com/alterstep/dnscrypt-osxclient/issues/41, about the delayed shutdown time. This was also noticed (and noted) on that issue by @Pmavrovic.

**Comment by alterstep** [comment]
I made changes to move all the files into the preferences pane directory.
There is nothing in /usr/local any more so if you had problems with installation on El Capitan they should be solved in the next release.
The unwanted side effect of the changes is that building a release has become more complicated. So I need to verify that all works as before, on different configurations.

**Comment by Pmavrovic** [comment]
Thanks for the excellent progress!

When do you think the next release will be complete?   

I was experimenting with Homebrew / DNScrypt install, but would prefer your method better.

Do you have a donations page?



Kind Regards,

		Paul Mavrovic

**Comment by Makedu** [comment]
Hi,

when can we expect a release with official support of OS X El Capitan (v10.11.1)?
Your current client v1.0.10 was released with 'Compatibility with OSX 10.11 beta 4'.

**Comment by ggamel** [comment]
Hi, @alterstep,

Do you have a target for release for 2016? Some time in January, perhaps? Also, is there a donations page/link to support your work?

**Comment by sergeb** [comment]
Hi,

It works fine on all of mine. Clean installs and upgrades.


On 19 Jan 2016, at 08:07, Greg Gamel <notifications@github.com> wrote:

Hi, @alterstep <https://github.com/alterstep>,

Do you have a target for release for 2016? Some time in January, perhaps?
Also, is there a donations page/link to support your work?

—
Reply to this email directly or view it on GitHub
<https://github.com/alterstep/dnscrypt-osxclient/issues/76#issuecomment-172667197>
.

**Comment by alterstep** [comment]
Try the new version!

**Comment by Pmavrovic** [comment]
I will and I will give feedback!
Thanks so much for updating

Paul Mavrovic, CISSP
