### ISSUE TITLE
Bypass issues

### ISSUE THREAD

**Issue by mickflemm** [alterstep/dnscrypt-osxclient#77]
On the latest build (1.0.10) separating domain entries to be bypassed with enter (e.g. copy / paste the list from text edit) doesn't work. The files are not generated on /etc/resolver/ unless the domain entries are separated using the space character (at least add something to the description letting the user know how to separate the entries on the text field because right not they are separated by enter on the example).

Also if the local domain is being added on the list it's ignored (exceptions-add.sh line 53) and in many cases resolving hosts using /etc/resolver/local doesn't work (I think it's an issue with OS X's resolver, it doesn't always obey /etc/resolver/local). In my case I had to manually create a file under /etc/resolver for the local domain (the one I have on /etc/resolv.conf) for things to work. At least leave the option of adding the local domain on the list of domains to be bypassed or -even better- create a file under /etc/resolver for it automatically.

Thanks a lot for your work, keep it up :-)

**Comment by mickflemm** [comment]
Also I noticed that there is an issue when switching wireless network. On the previous wireless network a file for the current local domain got created on /etc/resolver but when the system switches to the current wireless network, this file doesn't get updated (or deleted) and so the OS tries to resolve everything on the local domain using the revolvers from the previous wireless network.

**Comment by alterstep** [comment]
@jedisct1 You wrote the code section to disallow the local domain in the bypass list, in 0123713679b113deb18057d3930b456d1035ecfa => Do you remember why???

**Comment by jedisct1** [comment]
I do :)

The reason is that when a you have a default domain, and you send a query for a name that does not resolve, your application is likely to retry with a new query, this time by appending the default domain.

So, if your default domain is `example.com` and you send a query for `very-embarrassing-site`, and that doesn't resolve, your system may send another query right after, for `very-embarrassing-site.example.com`.

If `example.com` is in your exception list,  `very-embarrassing-site.example.com` will be sent in plaintext, right to your company's logging firewall, or whatever was defined as a local resolver to use for exceptions.

That mostly destroys the whole point of using DNSCrypt.

**Comment by mickflemm** [comment]
That doesn't make much sense, unless you are using a VPN connection the company's logging firewall can also log your HTTP/HTTPS request to `very-embarrassing-site`, it's actually more probable to log the HTTP/HTTPS queries than DNS requests (most companies use transparent proxies), if the proxy doesn't log it the load balancer / IDS will. Hiding your DNS queries is not a privacy measure unless e.g. you use ToR (or a proxy in general) and want to also pass DNS requests over it.

DNSCrypt is much more useful for protecting yourself against DNS protocol attacks. DNS is unencrypted and unauthenticated (unless you use DNSSec which most sites don't use and even if they do your local DNS server probably doesn't know about it -for web traffic there is a plugin on firefox for that btw-), it also uses UDP which makes it much easier for an attacker to inject replies and in general mess with you (e.g. redirect you to a malicious site). Using DNS over HTTPS or in general over an authenticated/encrypted channel is much better, at least that's why I use DNSCrypt. Security is not only privacy, it also includes availability and integrity and your solution hurts them both.

***Some more details on the issue I have:***
When firefox asks for `x.example.com`, `example.com` is the local domain and `local` is on the bypass list, it works. The standard resolver will see that `example.com` is the local domain, use `/etc/resolver/local` and ask the local DNS that knows about `x.example.com` (so I'm able e.g. to login to the corporate webmail). When I try connecting to a samba server on the local domain, the OS uses a different resolving strategy, it won't resolve `samba-share.example.com` against `local` -it ignores the local domain- and try to hit it directly through the default entry on `/etc/resolv.conf` (since there is no entry for `example.com` on `/etc/resolver/`). Now the public DNS server I'm using on DNSCrypt obviously doesn't know about `samba-share.example.com` and I end up with a non-working setup.

The reason this happens is probably because although the samba share is on the local domain, the A.D. controller isn't (yup it's a weird setup but have in mind that domains are application layer things, a host or an IP might map to multiple domains, it's perfectly normal and it's actually how virtual web hosting works), it's on another more "private" domain and the initial request is made against the A.D. controller (for authentication and redundancy reasons) which then redirects me to the samba share on the local domain. Probably because it's redirection or for some other reason the OS doesn't check if the request is against the local domain or not, it just hits it directly. That's a bug on the OS X's resolver, it should always take into account the local domain but it might be there for a reason I'm not aware off (someone else's bug).

Now what's more secure ? Allowing the user to bypass the local domain by name through the UI so that he/she can access such services on the local domain or having him/her logging in as root through su and do it manually by creating the `/etc/resolver/example.com` entry ? Or is it better to disable DNSCrypt -and be vulnerable to DNS attacks for everything outside the local domain- ?

Let's look at it another way, by default `local` is part of the bypass list (or at least it's possible to put it there). It's much more probable that the application you mention in your scenario asks for `very-embarrassing-site.local` instead of resolving `local` to `example.com` and ask for `very-embarrassing-site.example.com`, not only that but is it really different allowing `local` to be bypassed but not `example.com` when `example.com` is the local domain ?

**Comment by jedisct1** [comment]
"DNSCrypt is much more useful for protecting yourself against DNS protocol attacks"

But if the protocol can be downgraded to plaintext/unauthenticated, it doesn't protect against anything any more.

Your app sends a query for `mybank` and gets `NX`. It retries over plain, unauthenticated DNS with `mybank.defaultdomain`. A malicious response for that query can be injected before the one from the resolver for your default DNS resolver.

I don't remember what the script does, but if your default domain name is actually called `local`, it shouldn't be bypassed either.

**Comment by mickflemm** [comment]
You are also downgrading the protocol when disabling DNSProxy because you can't work with it right ?

`.local` is a special domain name according to [IANNA](https://www.iana.org/assignments/special-use-domain-names/special-use-domain-names.xhtml) that maps to the local domain. It's the default way of doing a request against the local domain (it's mostly the same as `.localdomain`, it's just a more standards compliant way of doing it). If by default domain you mean the domain on `/etc/resolv.conf`, that's also the local domain (the one DHCP assigns you to). Right now users can create an entry for `local` and `localdomain` but not for the actual domain (`example.com` on our previous examples). Actually in order to be able to resolve hosts on the local domain, the script already creates files on `/etc/resolver` for various local tlds used by common DSL routers (such as `lan`, `belkin`, `domain`, `fritz.box`, `routerlogin.net` etc) automatically which can be an even bigger risk than what you mention (there is no check if any of these are the actual local domain assigned to you by your DHCP -especially `routerlogin.net` and `nowtv.com` seem very interesting for attack scenarios-). Your current approach only works for home networks, it won't work on corporate environments. Either let users put their local domain by name on the list or do it for them (as you do it for `lan` etc) but also for corporate domains (of course you can't know them in advance so that won't work).

The proper solution to what you are saying would be to have DNSCrypt handle that scenario. DNSCrypt can see both requests to `mybank` and `mybank.defaultdomain` so it knows that the second one is a re-try and skip it. If it sees a request directly to `server.defaultdomain` it should try resolving that against the default DNS servers it got from DHCP (the original resolvers on /etc/resolv.conf) so that it doesn't break communication with servers that are only available on the local domain and only resolvable by the local domain's DNS servers. That way you won't need all these default bypasses on `/etc/resolver`, I won't have to manually bypass the local domain by name and everyone will be happy.

**Comment by jedisct1** [comment]
If names within the default domain can be resolved by the DNSCrypt server, you don't want them to be sent unauthenticated to the DHCP-provided resolver. The problem with the default domain is that unlike other zones that are in the bypass list, they get queries that had originally nothing to do with the zone.

**Comment by alterstep** [comment]
The problem is not about bypassing domains but about using a default domain.

Simple fix! Don't configure a default domain!

Or: document that the default domain cannot be bypassed. A bypass for that domain is possible only if it's not set as the default domain any more.

**Comment by mickflemm** [comment]
But what happens if DNSCrypt can't resolve them ? It's highly unlikely that a public DNS server will be able to resolve the hosts on my local (home/university/corporate/whatever) domain. It needs to try tne one provided by the DHCP.

**Comment by alterstep** [comment]
If the default domain is not set or if it is set to a public domain, all is good!
To resolve names only known by a local resolver, use the fully qualified domain name instead of only the host name.

**Comment by mickflemm** [comment]
@alterstep the domain on `/etc/resolv.conf` is the local domain your host is being assigned to by the DHCP server, ignoring it is not a solution (think of domain requests, smb/cifs etc).

Also hosts on a public domain doesn't mean that they are always resolved by public DNSes. Let me give you an example: `company.com` is a public domain, the public DNS server resolves `www.company.com` along with the mail server etc. Internally the company has a set of servers protected by a firewall that still use `company.com` as their domain but are not accessible from the internet and are not resolvable through the public DNS. Now you work for that company and use DNSCrypt, you'll try to access one of the local servers but DNSCrypt will only try to resolve them on the public DNS server, it'll get a failure and you won't be able to work unless you create a file for `company.com` under `/etc/resolver` (a bypass rule). So even if you do ignore the local domain on `/etc/resolv.conf` it won't solve the issue, it'll let you create the file and put the bypass rule there but you won't be a member of the domain -at least not to your OS-.

**Comment by alterstep** [comment]
But if you create a file for company.com but company.com is not the default domain, this will work!

**Comment by mickflemm** [comment]
There is no such thing as "default domain", it's the local domain, you can't just ignore it ! What if someone on the internal network redirects me using hostnames only ? How would that work ?

**Comment by alterstep** [comment]
OSX calls this "search domain" and allows more than one "search domains".
None of them have to be local domains! My search domain is my company domain, which is a public domain, on which all the names are public. It's convenient to type only the host name in ssh. But I can ssh to the same hosts if I add the domain name. I never use the local random domain assigned by my home router.
True, if someone on the internal network redirects you using hostnames only, and without the expected domain being configured as a search domain, it will not go anywhere, of course. But it's easy to try again with the domain name.

**Comment by jedisct1** [comment]
`man ssh_config` :)

**Comment by mickflemm** [comment]
If it's a www link it's easy, if it's another service where e.g. there is no user interaction, it's not easy to force the service to do an FQDN request instead.

**Comment by alterstep** [comment]
If there is no way to enter the full domain name, add dnscrypt to the local server. If you can't, you have to deinstall this application.

**Comment by mickflemm** [comment]
So instead of reverting a patch that doesn't make much sense (since you can already bypass `.local` and `.localdomain` and you already by default do that for home networks via the `.lan` etc default bypasses) you are telling me to force the company's network admin to put dnscrypt on the local dns or else uninstall the application. Sorry for using your software guys, my mistake...

**Comment by alterstep** [comment]
You uninstall or pause the application 5 minutes to access an unqualified domain: this is intentional, you know what is happening.

The application leaks queries because of the search domains: most users do not expect that from the application, this is a vulnerability.

The same limitations exist with a VPN. If your company's network admin doesn't want you to use dnscrypt, it's better to not use it.

**Comment by mickflemm** [comment]
In order for this to work I'll have to close all other applications that might do DNS queries on that 5 min window. You assume that the only application that runs is the weird one. Also please tell me why is `.lan` any different or `routerlogin.net` ? Isn't `routerlogin.net` a local domain that's by default being bypassed right now for the same reasons I ask you to let me bypass my equivalent of `routerlogin.net` ?

**Comment by alterstep** [comment]
If routerlogin.net is your default domain, a routerlogin.net file will not be present.

**Comment by mickflemm** [comment]
But what if it's on the list of search domains ? Check out `get-current-default-domain.sh` it only uses the `domain` entry, it ignores the `search` entry. So all an admin has to do to get the leaked queries logged is to anounce a search domain through DHCP (it's the `option domain-search domain-list`) and put `routerlogin.net` there. Now according to resolver(5) `Unqualified queries will be attempted using each component of the search list in turn until a match is found.`. This is leakage from the OS, guaranteed !

**Comment by alterstep** [comment]
I would gladly accept a pull request to improve this.

**Comment by mickflemm** [comment]
And again render DNSCrypt unusable because these might be valid search domains needed for proper operation on the local domain. I'm just trying to understand your point of view here. Let's say I have a browser open with multiple tabs, some of them point to `very-embarrassing-site`, and if DNSCrypt is blocked (e.g. on a captive portal or because the admin blocks it), there is a checkbox on the UI `automatically disable if blocked` that allows the user to have a working environment even if DNSCrypt can't connect.

You don't care about leakage there and there is no warning to the user when enabling that option that says anything about information leakage or privacy issues. Even in the case of captive portal (the one mentioned on the tip) until the user passes the captive portal the browser will already have made DNS queries for the open tabs (you could play with 1.1.1.1 there which is in most cases the captive portal's address to improve this too if you want to but it's not guaranteed and it'll again break operation in some cases).

So there are already ways to have information leakage on the current setup, and even if you try to improve them DNSCrypt cannot in any way guarantee privacy, you will never be able to "fix" that issue ! If a transparent proxy is there (which is the case in most public environments -even captive portals use transparent proxies to work-) there is nothing DNSCrypt can do to hide the fact that user tried to open `very-embarrassing-site`. Telling users that DNSCrypt protects their privacy is a false statement, it only does that if you work over an anonymizing VPN or an anonymous proxy used by multiple users and even then you can't be sure about it unless you trust that VPN or proxy completely.

If you move to the scenario when DNSCrypt blocks any query on the default revolvers (by not allowing the user to bypass DNSCrypt or disable it until unblocked) you are doing a DoS attack on your users by hurting the availability of the DNS service e.g. in cases where requests are being made using hostnames like mine. DNS service is a critical service and hurting its availability is a very bad choice (you basically break network connectivity) . You are doing this based on the assumption that in some way this protects their privacy but the fact is that this only protects their privacy if:

a) There is no transparent proxy or they are using a trusted anonymizing proxy/VPN
b) They miss-typed the domain address of `very-embarrassing-site` (because if they typed it correctly it'll resolve the first time through DNSCrypt so the application won't try to resolve it against the local domain, if it's on the local domain it's probably not a `very-embarrassing-site`, at least not to the domain admins).

DNSCrypt can only guarantee integrity of the DNS service and that's its power basically, it's not an anonymizer or a privacy protection tool and it can't be one, not at the DNS level.

**Comment by alterstep** [comment]
This is what the "About" tab says:

The "Automatically disable if blocked" feature automatically disables DNSCrypt when DNS queries are not able to reach the DNSCrypt resolver. This can happen on public WiFi networks that require going through a captive portal before you can access external networks. This function is only provided for conveniency. When enabled, the protocol can be easily downgraded by third-parties. In other words, when the "Automatically disable if blocked" feature is enabled, this software doesn't provide any security at all against active attackers, but it can still be useful against passive attackers and in order to bypass DNS censorship. Don't enable it unless you are frequently roaming and you don't want to manually disable/enable DNSCrypt.

**Comment by mickflemm** [comment]
So why don't you allow users for conveniency to bypass the local domain by name too ? Or at least bypass specific hosts ! You are not even allowing that, your script does `grep -c ".*${default_domain}"` so even if I want to bypass just the servers I need to talk to on the local domain I can't !

**Comment by alterstep** [comment]
I understand that the application doesn't do what you want, but it's better to block queries in some cases than being insecure by default. What you are suggesting lowers the security for everybody.
The scripts are easy to modify, so you can modify them on your computer, and you know how to do it. For everybody else this is not a good idea.

**Comment by mickflemm** [comment]
O.K. I'll do that, thanks for your time
