### ISSUE TITLE
Binary download not current

### ISSUE THREAD

**Issue by kirk-kerekes** [alterstep/dnscrypt-osxclient#79]
It appears that the binary installer (dmg) download is not the current version, as the .dmg dates from July, and the project was updated around 17 days ago to package the innards differently for El Capitan.

**Comment by alterstep** [comment]
The source code of the project was updated, but the next version hasn't been released yet!
The binary installer will be updated after the next version is finished.

**Comment by kirk-kerekes** [comment]
I know the process only moves as fast as it can move, but El Capitan adoption is very high, and DNSCrypt fails pretty quietly. 

I suspect a majority of users do not know it is not working. 

Kirk Kerekes 
(iPhone)
