### ISSUE TITLE
Why is apple.com domain mandatory for the app to work?

### ISSUE THREAD

**Issue by elgab** [alterstep/dnscrypt-osxclient#82]
Hi, i wish to block *apple* at DNS proxy level, please don't lecture me that is bad and useless...
Why the proxy need to connect to apple.com to work? I use dnsproxy on windows and android and no such requirement exists; from what i know it only require NTP for precise system time.

**Comment by alterstep** [comment]
... to verify that the configuration is good to use, and that it is not hijacked by a local router, firewall or ISP.
If apple.com doesn't resolve, nothing will work, so it will not enable dnscrypt, and keep the previous configuration instead.

**Comment by elgab** [comment]
I've kinda anticipated this but why not in the spirit of free software use a neutral domain?

**Comment by alterstep** [comment]
We need a name that:
1) Everybody is familiar with
2) Is unlikely to be blocked/firewalled
3) Responds all the time
4) Is not Google

apple.com fits all these requirements.

**Comment by dnscryptme** [comment]
Apple is ok in my opinion

**Comment by chew-z** [comment]
I have changed apple.com to ip4.icanhazip.com and google-public-dns-a.google.com to github.com for myself. 
You could also try http://start.ubuntu.com/connectivity-check.
Just saying..

**Comment by dnscryptme** [comment]
I'm a bit confused now...

> 4) Is not Google

But we find _google-public-dns-a.google.com_ in _check-local-dns.sh_ and _check-hijacking.sh_?

**Comment by alterstep** [comment]
There are two checks for two different things!

- google-public-dns-a.google.com is to check that the DNS returns correct IPs. This name will always return 8.8.8.8, so this is what we check. Another name like github.com will not always return the same IP address! And for this check, it's only a DNS query, made via dnscrypt, through the dnscrypt resolver so Google doesn't learn anything.
- the other name, apple.com is a HTTP query. We check that the web page has "apple" in it and not "this is the macdonald's wifi portal please click here to connect". You're on a mac, already constantly accessing apple.com, and the company is unlikely to have a web site that doesn't say "apple" on it anytime soon. So it's a good choice!
ip4.icanhazip.com will make people think they have a virus, and non-geeky people dont know what ubuntu is.

**Comment by elgab** [comment]
You can ditch Google DNS#1 for "resolver1.opendns.com", chew-z and dnscryptme.
as alterstep said there is no data leak here.
For Apple i have to think about some mainstream alternative myself.
The purpose of this changes are only to allow wildcard blocking of: apple and google and help you read dnscrypt-query.log if you use it.
The normal Apple user will not even dream about doing such horrible things :)

**Comment by dnscryptme** [comment]
I would prefer it if the DNSCrypt-OSXClient uses one of OpenDNS (instead of Google) by default

    208.67.222.222 (resolver1.opendns.com)
    208.67.220.220 (resolver2.opendns.com)
    208.67.222.220 (resolver3.opendns.com)
    208.67.220.222 (resolver4.opendns.com)

**Comment by alterstep** [comment]
No thanks. Cisco already collects and sells enough personal data, in addition to having backdoors in their products.

**Comment by dnscryptme** [comment]
:-D Ok, good point.

**Comment by alterstep** [comment]
A viable alternative would be some domain name reserved by the IANA, which already returns the same IP. Is there any? Root DNS servers cannot be used because their IP change, too.

**Comment by alterstep** [comment]
And it has to be something that everybody knows. Non geek people don't even know what cisco is. But they know there is an apple on the back of their laptop.

**Comment by alterstep** [comment]
There is no real problem and we haven't found any alternative in 2 days, so let's keep what we have.

**Comment by elgab** [comment]
I've replaced the curl for apple.com with https debian.org, and grep for "Debian".
Now I can use the nazi wildcard filter *apple* when needed.

Google DNS as @alterstep mentioned is not security/privacy related as it is resolved via the dnscrypt proxy... and i don't need to wildcard block *google*
