### ISSUE TITLE
Include default DNS Resolvers in 'When not using DNSCrypt...' field

### ISSUE THREAD

**Issue by TraderStf** [alterstep/dnscrypt-osxclient#86]
May I suggest to add these resolvers in the field 'When not using DNSCrypt, us the following static DNS servers:'

91.239.100.100 89.233.43.71 2001:67c:28a4:: 2002:d596:2a92:1:71:53::

They are provided by activists for a free uncensored internet.

www.censurfridns.dk
anycast.censurfridns.dk	 / 91.239.100.100 / 2001:67c:28a4::
ns1.censurfridns.dk	 / 89.233.43.71   / 2002:d596:2a92:1:71:53::

<i>(FYI 89.104.194.142 is an old one, no more mentioned on their site)</i>

Or the usual (censoring/tracking)
https://developers.google.com/speed/public-dns/docs/using

Other.
https://www.opendns.com/home-internet-security/
http://www.verisign.com/en_US/innovation/public-dns/index.xhtml
http://securedns.dnsbycomodo.com/
https://www.opendns.com/home-internet-security/
https://dns.norton.com/homeuser.html
he.net...

**Comment by TraderStf** [comment]
I just noticed, if you use ',' comma instead of space only, the comma is replaced by a space.
I quickly made few tests, other 'invalid' characters are not removed, don't know if it can cause a problem/crash.

**Comment by alterstep** [comment]
They may not be accessible in some countries or from some networks. Not using the default resolvers also prevents connection to the Wifi login page in coffee shops and hotels.
