### ISSUE TITLE
Sometimes DNSCrypt blocks SMTP connections of Thunderbird

### ISSUE THREAD

**Issue by Nomis101** [alterstep/dnscrypt-osxclient#88]
I'm on OS X 10.11 and using Thunderbird (currently TB 43, but the issue can be seen with all versions I've tested) for email. Sometimes it is happening that I can not send emails. TB shows instead the message: "Failure when sending the message, the mail server is replying mailbox unavailable. 
Sender adress is not allowed. Please check if the email adress in the account settings is correct and repeat the process."
It helps for some time if I open the DNSCrypt preferences and change the name server. Than I can send emails again. But the error happens some days later again. Uninstalling DNSCrypt is the only long-term solution I've found.

It don't think this is an issue of OS X, because I found this:
http://www.cnet.com/forums/discussions/problems-with-open-dns-crypt-and-thunderbird/
And he is on Linux.

**Comment by alterstep** [comment]
This is probably unrelated to DNSCrypt, but your ISP requires you to use their DNS servers. They return a different IP for their internal services like mail servers, than what the rest of the world sees.
As described in the article you linked, use the IP in Thunderbird instead of the name.
