### ISSUE TITLE
Fallback DNS default value

### ISSUE THREAD

**Issue by adam1x** [alterstep/dnscrypt-osxclient#90]
The default value (if left blank) for fallback DNS server when DNSCrypt is not enabled is DHCP-assigned servers. However, this introduces problems when there is a need for different configurations on different networks (different Wi-Fi's and VPNs). For example, for my regular Wi-Fi connection, I'd only need fallback DNS servers as OpenDNS and Google DNS (both of which are not DHCP default servers); while on my VPN connection, I would need the DHCP default servers.

Is it possible that we can have the default value set to preserve whatever setting there is in system preferences already?

**Comment by alterstep** [comment]
This is too complicated, even for the user interface. Sorry, I'm not doing to work on a change like this.

**Comment by adam1x** [comment]
ok I understand. Thanks anyway!
