### ISSUE TITLE
Blocking IP's and hosts

### ISSUE THREAD

**Issue by chew-z** [alterstep/dnscrypt-osxclient#91]
I do alternate between dnsmasq and DNSCrypt-OSXClient. I am using  DNSCrypt-OSXClient 90% of the time now but I do feel kind of naked without all sophisticated IP and hosts blocks filtering (malware, spying and other bad guys) that is so easy to configure in dnsmasq.

If I may suggests some improvements to DNSCrypt-OSXClient it would be the ability to download IP/domain name block lists from file / http address. 

Something like [Emerging Threats](http://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt) IP list or host lists generated by projects like [Steven Black/hosts](https://github.com/StevenBlack/hosts)

**Comment by jomo** [comment]
Couldn't you just put those lists into `/etc/hosts`?

**Comment by GitTheHellOutaHere** [comment]
I tried to use dnsmasq, but it requires too much scripting - I just don’t see the benefit to what it does for all the time & hassle involved with setting it up.

DNSCrypt is simple, but it doesn’t cache, which is the whole purpose of dnsmasq, isn’t it?
I don’t think DNSCrypt is a _replacement_ for dnsmasq, optimally they should be used together.

**Comment by chew-z** [comment]
Learning dnsmasq is well worth the effort. It's not just caching, it helps to understand DNS better and fine tune some details. 

I have abandoned dnscrypt-osxclient altogether. Alterstep's scripts are top class and I have learned a lot from them but in the end they do more harm then good. They have never been reliable with plugins and constantly late to the party - unnecessarily restarting dnscrypt and loosing to mDNS. With proxy and VPN and captive portals and Mac going to sleep - it was a nightmare.

I have compiled pure dnscrypt-proxy with plugins and it works spotless together with dnsmasq. I could recommend some plugins especially [masquerade plugin](https://github.com/gchehab/dnscrypt-plugin-masquerade) and [geoip blocking](https://github.com/jedisct1/dnscrypt-plugin-geoip-block). Took me few hours to build and make them running but it was fun.

In my scenario I am blocking hosts with dnsmasq but AAAA and certain IP's from (from firehol's list) with dnscrypt-proxy plugins.

**Comment by GitTheHellOutaHere** [comment]
I don’t think I _want_ to know more about DNS, I just have my one little home computer to worry about and I feel it’s already safer than most. I suspect that DNS cache poisoning is a very, very small problem, and as long as my computer is connecting to websites like it should, there’s little need for security measures like the ones I’ve already implemented.

I only wanted to use dnsmasq to cache DNS entries to supposedly speed up browsing.

I use DNSCrypt and one of the Steven Black hosts files with my own additions added, also DNSSECValidatorPlugin and TLSAValidatorPlugin (although I question their effectiveness for actually protecting me). I use Viscosity to connect to VPN servers when necessary.

What I really need is an effective JavaScript blocker for Safari.
[JS Blocker](https://goo.gl/5BGKzu) used to work fairly well, but seems to be incompatible with Safari 10+. [Third Party Blocker](https://goo.gl/i8QsSl) is virtually useless.

Disabling JS in the prefs makes surfing nearly impossible.
