### ISSUE TITLE
list of addresses and ports

### ISSUE THREAD

**Issue by 1-61803** [alterstep/dnscrypt-osxclient#92]
Originally I opened this issue at dnscrypt (https://github.com/jedisct1/dnscrypt-proxy/issues/370).

Dnscrypt doesn't seem to work on a host with restricted outbound connections. For example, if apple:80 is blocked it doesn't work at all. I thought allowing dnscrypt on 443 would do, but it doesn't. In fact, besides 80 and 443 other ports need access and whole bunch of other addresses, even for one DNS service, when I'd actually expect 2 IPs per service on 443.

Could you explain this and provide a thorough list?
Can apple:80 be set to something else?

**Comment by chew-z** [comment]
Please look at [this discussion](https://github.com/alterstep/dnscrypt-osxclient/issues/82). apple.com:80 is used to verify that the connection is legit - not redirected by ISP, captive portal etc. It is fairly easy change in scripts and you could use whatever you like. Look into check-hijacking.sh script.

**Comment by 1-61803** [comment]
Thanks for the reference. I barely use Apple's site, and Google's, not directly. I wonder how dnscrypt-proxy actually checks the connection.

**Comment by chew-z** [comment]
alterstep code is very readable, beautifull code. It does curl to apple.com and then fgrep for a pattern to confirm that it is apple.com page indeed. 
Similarily it digs for google-public-dns-a.google.com and confirms its well known IP. 
You can modify the code easily, I did myself for fun. I do curl icanhazip.com and dig github.com, you can use whatever works for you.

**Comment by 1-61803** [comment]
Ok, but what's the rationale for sending those queries? It wouldn't work nonetheless if it couldn't establish a direct connection to the server, and then just signal this event in the menu bar or via a notification mechanism.

**Comment by alterstep** [comment]
Wi-Fi access points can do a lot a funny things.

At the local train station, if I connect to the Wi-Fi and type apple.com, it will connect, but load a page that is not Apple page. It's a page that forces me to watch a video, then forces me to accept the terms of use, or enter my credentials if I have a prepaid account.
Then, I can finally access the internet, and typing apple.com goes to the correct site.

Before having gone through all these steps, if I use anything but the DNS settings sent by the access point DHCP server, I can't connect anywhere. Internet is not accessible, the access point page is not displayed, iCal is displaying error popups.
Although I can establish a connection to apple.com, I don't have internet access, and using a DNSCrypt server blocks everything. After passing the portal, internet is finally reachable, and DNSCrypt can also be used.

The purpose of these simple tests is to detect both scenarios.

**Comment by 1-61803** [comment]
I experienced some of those problems myself.

I don't know `dnscrypt` specification, but why not just try to authenticate 3 times to the server and then give up with a notification and use whatever dhcp offers? Pretty simple — or am I missing something?

Which version did you introduce these methods in?

**Comment by alterstep** [comment]
dnscrypt is not like SSL. If you send a query to the server and don't get a response you don't know why.

**Comment by 1-61803** [comment]
Which version did you introduce these methods in?

**Comment by alterstep** [comment]
It's very old, maybe from the first version.

**Comment by 1-61803** [comment]
0.19 didn't had it. Anyway, as I said, sending 3 queries, giving up with a notification ("couldn't contact dns server, check with your netadmin, your're probably using a wifi spot") and use whatever dhcp offers, would be ok for most cases. If you could at least offer a fallback option without any queries to big brother…

**Comment by alterstep** [comment]
You don't understand that this query is not sent to Apple.

**Comment by alterstep** [comment]
> 0.19 didn't had it

It did. With a different query: https://github.com/alterstep/dnscrypt-osxclient/blob/0.19/DNSCrypt-Preference-Pane/DNSCrypt/extra/usr/scripts/check-hijacking.sh#L6

You are proposing to send 3 queries instead of 1.

**Comment by 1-61803** [comment]
> You don't understand that this query is not sent to Apple.

:doublefacepalm: ha, I do actually, but I should have meant 'asking for big brother'.

> It did. With a different query

You're right. I permitted the outgoing connection long ago. At least, could you add a way to deactivate this query and/or specify another website in a plist?

**Comment by alterstep** [comment]
If you block Apple, how do you keep your system and apps up to date?

**Comment by 1-61803** [comment]
I never said I completely block it, did I? Anyway, since you asked, I do it manually and review the new crap that they introduce before breaking my workflow.
