### ISSUE TITLE
support for http proxy ?

### ISSUE THREAD

**Issue by ka2er** [alterstep/dnscrypt-osxclient#93]
Hi,

do you support usage behind an http proxy ?
For security reason my corporate has denied all outgoing traffic.
Only 80/443 traffic trough http proxy is allowed.
And DNS protocol is only enabled for internal domains.

Thks

**Comment by jedisct1** [comment]
It doesn't, sorry.

The purpose of this software is not to bypass your company policies.

**Comment by ka2er** [comment]
ok thanks for the info (merci).

It was not for bypassing only in the purpose of testing and learning about.
