### ISSUE TITLE
TXT record lookup failures

### ISSUE THREAD

**Issue by Synchro** [alterstep/dnscrypt-osxclient#94]
I'm not entirely sure where this problem is happening, but it's definitely related to dnscrypt and I'm using the OS X client for it. The problem is that lookups for some TXT records are returning the wrong records. Other record types seem to be OK. It seems to be a problem with the dnscrypt server it's connecting to, as if I override that (and talk directly to authoritative servers) it returns correct values. For example:

`dig +short txt mail2048._domainkey.example.com` (with dnscrypt disabled):

```
"v=DKIM1\; k=rsa\; " "p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvMnb3KoWIrwrea7gtjVNAj1q2IrCut6ehJemnL1G8IfQzRB2FPtsFA1lbjHexIDGFGU4uAu0x4ygxr3z54KIK1iz+jQEMRxw930ndH2UeHTpGFq1eoSZjALGjWc6QqQqPK9jQDQ6txmQ6UjmCG8jGMPEK+GBGYZba/Bpyz5rOV8EvEWI8M1sg1EKtk8ZIvpb5MyQP+oq6M2VuX"..."
```

`dig txt mail2048._domainkey.example.com` (with dnscrypt enabled):

```
mail2048._domainkey.example.com. 3600 IN CNAME example.com.
example.com.  9747    IN      TXT     "v=spf1 mx a -all"
```

This looks like it's mistakenly looking for an A record (which goes via a CNAME), which then returns the aliased name and then looks up the TXT record on that, which happens to line up with my SPF record.

I'm not sure where this should be reported, so I'm starting here.

**Comment by jedisct1** [comment]
Hi Marcus,

What DNSCrypt resolver are you using?

DNSCrypt itself just handles the transport, so the issue is likely to be a bug in a specific resolver.

`example.com` doesn't have DKIM records. Do you have actual queries I could use in order to diagnose this?

**Comment by Synchro** [comment]
I'm using "DNSCrypt.org France" - most of the others I've tried failed to connect at all. You can test using `cham01.chamsocial.com` in the above queries instead of `example com`.

**Comment by jedisct1** [comment]
OK, the issue is specific to this resolver, which is running an experimental DNS cache.

The bug is likely to be due to how the qname normalization process handles the `_` character.
Thank you so much for spotting and reporting this bug!

I'm going to fix it shortly.

**Comment by Synchro** [comment]
Great, thanks! I guessed that it might be something to do with `_` chars as they are not allowed in hostnames, but are in other record types, and not that many use DKIM yet.

**Comment by jedisct1** [comment]
Bug fixed and new version deployed :)

Thanks a ton for spotting this!
