### ISSUE TITLE
1.0.11 Still doesn't seem to work.

### ISSUE THREAD

**Issue by kirk-kerekes** [alterstep/dnscrypt-osxclient#96]
Never connects. OS X 10.11.3 (15D21). 

Recent log messages containing "DNSCrypt" spanning installation, restart and failure to launch:

3/3/16 8:45:22.000 PM kernel[0]: hfs: mounted dnscrypt-pkg on device disk2s1
3/3/16 8:45:22.480 PM mds[68]: (Volume.Normal:2464) volume:0x7fdfa1863a00 ********** Bootstrapped Creating a default store:1 SpotLoc:(null) SpotVerLoc:(null) occlude:0 /Volumes/dnscrypt-pkg
3/3/16 8:46:00.220 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptMenuBar[441]) Service exited due to signal: Terminated: 15
3/3/16 8:46:00.487 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptConsoleChange) ThrottleInterval set to zero. You're not that important. Ignoring.
3/3/16 8:46:00.498 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptControlChange) ThrottleInterval set to zero. You're not that important. Ignoring.
3/3/16 8:46:00.711 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
3/3/16 8:46:02.071 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
3/3/16 8:47:13.024 PM deleted[481]: normalizeUserMountpoint:736 volRoot failed for /Volumes/dnscrypt-pkg
3/3/16 8:47:13.024 PM deleted[481]: _validateVolume:758 unable to normalize volume: "/Volumes/dnscrypt-pkg", vol: (null)
3/3/16 8:47:17.738 PM com.apple.xpc.launchd[1]: (com.opendns.osx.DNSCryptMenuBar[554]) Could not find and/or execute program specified by service: 2: No such file or directory: /Applications/DNSCrypt-Menubar.app/Contents/MacOS/DNSCrypt-Menubar
3/3/16 8:47:17.738 PM com.apple.xpc.launchd[1]: (com.opendns.osx.DNSCryptMenuBar[554]) Service setup event to handle failure and will not launch until it fires.
3/3/16 8:46:49.942 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
3/3/16 8:46:50.996 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
3/3/16 8:46:53.334 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
3/3/16 8:46:54.465 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
3/3/16 8:46:57.061 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.

![dnscrypt](https://cloud.githubusercontent.com/assets/3299663/13516827/6d4a8a76-e183-11e5-953f-3a1696844660.png)

**Comment by kirk-kerekes** [comment]
Note log line:

"3/3/16 8:47:17.738 PM com.apple.xpc.launchd[1]: (com.opendns.osx.DNSCryptMenuBar[554]) Could not find and/or execute program specified by service: 2: No such file or directory: /Applications/DNSCrypt-Menubar.app/Contents/MacOS/DNSCrypt-Menubar"

It is absolutely correct -- the installed binary is named:
                      "DNSCrypt Menubar" 
instead of:
                      "DNSCrypt-Menubar". 

_Xcode is a hard taskmistress._

**Comment by alterstep** [comment]
But: com.opendns.osx.DNSCryptMenuBar.plist does not exist in my package!
This is a leftover from a very early version of the tool, remove it!

**Comment by alterstep** [comment]
I would recommend uninstalling it, and also removing any plist file starting with com.opendns.osx.
Then reinstall it correctly.

**Comment by kirk-kerekes** [comment]
Tried that as best I can -- no joy. Uninstalled current version, Deleted everything on HD with "DNSCrypt" in it except email, web history and the new installer. Reinstalled. Still does not run.

Current log dump:

3/6/16 9:48:21.690 PM deleted[405]: normalizeUserMountpoint:736 volRoot failed for /Volumes/dnscrypt-pkg
3/6/16 9:48:21.690 PM deleted[405]: _validateVolume:758 unable to normalize volume: "/Volumes/dnscrypt-pkg", vol: (null)
3/6/16 9:51:29.531 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
3/6/16 9:51:29.685 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptMenuBar[524]) Service exited due to signal: Terminated: 15
3/6/16 9:54:43.116 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptConsoleChange) ThrottleInterval set to zero. You're not that important. Ignoring.
3/6/16 9:54:43.127 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptControlChange) ThrottleInterval set to zero. You're not that important. Ignoring.
3/6/16 9:54:43.310 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
3/6/16 9:54:44.400 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
3/6/16 9:57:25.641 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
3/6/16 9:57:25.772 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptMenuBar[459]) Service exited due to signal: Terminated: 15
3/6/16 10:02:52.870 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptConsoleChange) ThrottleInterval set to zero. You're not that important. Ignoring.
3/6/16 10:02:52.883 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptControlChange) ThrottleInterval set to zero. You're not that important. Ignoring.
3/6/16 10:02:53.097 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
3/6/16 10:02:54.150 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
3/6/16 10:03:29.726 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.

**Comment by ggamel** [comment]
Not sure if this will help, but try the following commands in Terminal/iTerm:

First:
`
$ pkgutil --pkgs | grep DNSCrypt
`

Followed by:
`
$ pkgutil --files com.whatever.DNSCrypt
`

Run the second command for each entry listed from the first command. This will list all files related, so might show you some you didn't catch.

**Comment by kirk-kerekes** [comment]
I had a “virgin” MBP that I had not attempted to install the new DNSCrypt on, so I ran the Uninstall command from the existing DNSCrypt “About” page, and then ran your first suggested script. The results were:

com.github.dnscrypt-osxclient.dnscryptClient.DNSCrypt-Menubar
com.github.dnscrypt-osxclient.dnscryptClient.DNSCrypt
com.opendns.osx.dnscryptClient.com.opendns.osx.DNSCryptConfigUpdater.pkg
com.opendns.osx.dnscryptClient.com.opendns.osx.DNSCryptMenuBar.pkg
com.opendns.osx.dnscryptClient.DNSCrypt-Menubar
com.opendns.osx.dnscryptClient.DNSCrypt-Menubar.pkg
com.opendns.osx.dnscryptClient.DNSCrypt
com.opendns.osx.dnscryptClient.DNSCrypt.pkg


I discovered that the DNSScript Menubar app had not been uninstalled. This has been true every time I have checked after an uninstall, on every device.

Before installation I deleted any “DNSCrypt” or “OpenDNS” items from the ~/Library hierarchy, the /Library hierarchy and the /Applications hierarchy. 

I looked for items in the Application Support directories, the Preference Panes directories, the LaunchAgents directories and the Preferences directories, in the three main directory trees (~/Library/, /Library, /System/Library/)

I have gotten DNSCrypt to install successfully on a Mac Mini (Late 2012), and MBP (Late 2011) but not on my MBA (Early 2014). Same procedure on all.
All are running the current release OS-X version. (10.11.3)
All have XCode and friends installed.

All have the firewall disabled and the installation security set to AppStore Plus Registered Developers. 
I tried setting the MBA to “Anywhere” before one install attempt, but it didn’t help. 

In all cases I have selected “Cisco OpenDNS” as the resolver.

**Comment by kirk-kerekes** [comment]
Here are the raw log messages that occurred during the initial install:

3/8/16 7:09:56.378 PM CoreServicesUIAgent[563]: Error -60005 creating authorization
3/8/16 7:10:31.700 PM mds[68]: (ImportServer.Normal:4689) Preparing for software update
3/8/16 7:10:31.706 PM UserEventAgent[48]: Failed to send message because the port couldn't be created.
3/8/16 7:10:31.947 PM lsd[374]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
3/8/16 7:10:32.100 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptConsoleChange) ThrottleInterval set to zero. You're not that important. Ignoring.
3/8/16 7:10:32.114 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptControlChange) ThrottleInterval set to zero. You're not that important. Ignoring.
3/8/16 7:10:32.463 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
3/8/16 7:10:32.474 PM mds[68]: (ImportServer.Normal:4704) Software update complete
3/8/16 7:10:32.565 PM mDNSResponder[97]: SIGHUP: Purge cache
3/8/16 7:10:33.063 PM UserEventAgent[48]: Failed to send message because the port couldn't be created.
3/8/16 7:10:33.090 PM lsd[374]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
3/8/16 7:10:33.101 PM lsd[374]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
3/8/16 7:10:33.121 PM lsd[374]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
3/8/16 7:10:33.139 PM lsd[374]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
3/8/16 7:10:33.496 PM mDNSResponder[97]: SIGHUP: Purge cache
3/8/16 7:10:33.501 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
3/8/16 7:10:33.629 PM com.apple.xpc.launchd[1]: (com.apple.AirPortBaseStationAgent) Service only ran for 1 seconds. Pushing respawn out by 9 seconds.

— and here are the log messages that occurred after the reboot, filtered down to those containing “dns” somewhere.

3/8/16 7:10:32.100 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptConsoleChange) ThrottleInterval set to zero. You're not that important. Ignoring.
3/8/16 7:10:32.114 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptControlChange) ThrottleInterval set to zero. You're not that important. Ignoring.
3/8/16 7:10:32.463 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
3/8/16 7:10:32.565 PM mDNSResponder[97]: SIGHUP: Purge cache
3/8/16 7:10:33.496 PM mDNSResponder[97]: SIGHUP: Purge cache
3/8/16 7:10:33.501 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
3/8/16 7:12:42.267 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
3/8/16 7:15:54.127 PM mDNSResponder[97]: mDNSResponder mDNSResponder-625.20.4 (Oct 23 2015 16:41:21) starting OSXVers 15
3/8/16 7:15:54.650 PM mDNSResponder[97]: mDNS_SetSecretForDomain: ERROR: Could not convert shared secret from base64: domain kkerekes.members.mac.com. key kkerekes.members.mac.com. 
3/8/16 7:15:54.675 PM mDNSResponder[97]: D2D_IPC: Loaded
3/8/16 7:15:54.676 PM mDNSResponder[97]: D2DInitialize succeeded
3/8/16 7:15:54.686 PM mDNSResponder[97]: Adding registration domain 266835881.members.btmm.icloud.com.
3/8/16 7:15:54.692 PM configd[57]: network changed: DNS*
3/8/16 7:15:54.857 PM mDNSResponder[97]: mDNS_SetSecretForDomain: ERROR: Could not convert shared secret from base64: domain kkerekes.members.mac.com. key kkerekes.members.mac.com. 
3/8/16 7:15:55.136 PM mDNSResponder[97]: SIGHUP: Purge cache
3/8/16 7:15:55.622 PM configd[57]: network changed: v4(en3+:192.168.1.103) DNS+ Proxy+ SMB
3/8/16 7:15:55.836 PM mDNSResponder[97]: SIGHUP: Purge cache
3/8/16 7:15:58.439 PM configd[57]: network changed: v4(en3:192.168.1.103) DNS Proxy SMB
3/8/16 7:15:58.467 PM mDNSResponder[97]: mDNS_RegisterInterface: Frequent transitions for interface en0 (FE80:0000:0000:0000:4AD7:05FF:FECE:F211)
3/8/16 7:15:58.618 PM mDNSResponder[97]: mDNS_DeregisterInterface: Frequent transitions for interface en0 (FE80:0000:0000:0000:4AD7:05FF:FECE:F211)
3/8/16 7:15:59.463 PM configd[57]: network changed: v4(en3:192.168.1.103) DNS* Proxy SMB
3/8/16 7:15:59.477 PM configd[57]: network changed: v4(en3:192.168.1.103, en0!:192.168.1.116) DNS Proxy SMB
3/8/16 7:16:06.879 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
3/8/16 7:16:30.088 PM com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.


I noted that the menu item seems to not be connected to the Preferences — while opening the preferences works from the menu, selecting Enable DNSCrypt from the menu does nothing except generate another "com.apple.xpc.launchd[1]: (com.github.dnscrypt-osxclient.DNSCryptNetworkChange) Service only ran for 0 seconds. Pushing respawn out by 1 seconds.”
message.

And when I select Enable DNSCrypt in the prefpane, failure is pretty much instantaneous. 

Is there any way to turn on more logging in DNSCrypt itself?

**Comment by alterstep** [comment]
Create a file named debug.enabled in /Library/Application Support/DNSCrypt/control

Useful logs will go to /var/log/dnscrypt-osxclient-debug.log

**Comment by kirk-kerekes** [comment]
Interesting. 

Tested DNSCrypt, before installing the debug flag file - failed as usual.  The menu item and the prefpane were not synced, and enabling DNSCrypt in the prefpane got nowhere. 

Installed "debug.enabled", noting that "control" folder was otherwise empty. 

Turned DNSCrypt off and on in the preface and it began working. 

When I selected Cisco OpenDNS in the control panel, a file appeared in the control folder: dnscrypt-resolver-name. 

Then, a while later, a zero-length file named "dnscrypt" appeared there. 

I noticed that when I dragged the debug.enable file into the control folder I did not get a password request. So I looked at the permissions. 

The /Library/Application Support/DNSCrypt/ is owned by System, as are all of its sub folders except for tickets, control and updates, which are owned by "me". 

Here is a snap of the folder hierarchy. The dates may be informative. 



I modified the "debug.enable" filename and DNSCrypt continued to work. 

Seems like there might be some sort of silent permissions issue somewhere. 

Kirk Kerekes 
(iPhone)

**Comment by alterstep** [comment]
So, what do you get in the debug log?

**Comment by kirk-kerekes** [comment]
I never looked — because the moment the debug.enabled file was installed, DNSCrypt started working. 

That was not what I expected. 

I also did not expect that disabling the debug mode would leave everything working, once it had “fixed” things.

And disabling the DNSCrypt logging deleted the existing logs, so there is no longer any history available

**Comment by alterstep** [comment]
We will never know then!

**Comment by kirk-kerekes** [comment]
So it would appear. 

Kirk Kerekes 
(iPhone)
