### ISSUE TITLE
Mac OS 10.11.4 and DNSCrypt 1.0.11

### ISSUE THREAD

**Issue by D1001** [alterstep/dnscrypt-osxclient#99]
After rebooting my mac running 10.11.4, I've been unable to use DNSCrypt 1.0.11, regardless of the resolver selected. The DNS Server settings in the Network pane switches from 127.0.0.54 to 192.168.1.1 continuously.

Edit: removed useless logs

**Comment by alterstep** [comment]
Can you turn on logging for the dnscrypt client? The logs you posted don't contain useful information regarding dnscrypt.

Create a file named debug.enabled in /Library/Application Support/DNSCrypt/control

Useful logs will go to /var/log/dnscrypt-osxclient-debug.log

**Comment by D1001** [comment]
Here you go. I also remember running into this similar issue in a previous build.
[dnscrypt-osxclient-debug.log.zip](https://github.com/alterstep/dnscrypt-osxclient/files/190079/dnscrypt-osxclient-debug.log.zip)

**Comment by JBey4you** [comment]
I second this, saying that DNSCrypt doesn't work anymore for me since OS X 10.11.4. See the video here: https://vid.me/9MYr

**Comment by alterstep** [comment]
Have you tried uninstalling and reinstalling it?
Can you enable debugging and post the logs?
Are you doing something weird such as blocking apple.com on your mac?

**Comment by JBey4you** [comment]
Just did, same result.
I have to do it then.
Nope.

**Comment by JBey4you** [comment]
Although, I need some help to give you what you're asking. What are the steps needed?

**Comment by alterstep** [comment]
Create a file named debug.enabled in /Library/Application Support/DNSCrypt/control

Useful logs will go to /var/log/dnscrypt-osxclient-debug.log

**Comment by JBey4you** [comment]
All right, tell me if it's enough:

`Tue Mar 29 18:57:46 CEST 2016 - DNSCrypt-OSXClient configuration changed
Tue Mar 29 18:57:46 CEST 2016 - Stopping dnscrypt-proxy
Tue Mar 29 18:57:46 CEST 2016 - Changing the DNS configuration to use the default DNS resolvers
Tue Mar 29 18:57:47 CEST 2016 - Flushing the local DNS cache
Tue Mar 29 18:57:57 CEST 2016 - DNSCrypt-OSXClient configuration changed
Tue Mar 29 18:57:58 CEST 2016 - Stopping dnscrypt-proxy
Tue Mar 29 18:57:58 CEST 2016 - Changing the DNS configuration to use the default DNS resolvers
Tue Mar 29 18:57:58 CEST 2016 - Flushing the local DNS cache
Tue Mar 29 18:57:59 CEST 2016 - DNSCrypt-OSXClient configuration changed
Tue Mar 29 18:57:59 CEST 2016 - DNSCrypt has been requested
Tue Mar 29 18:57:59 CEST 2016 - Changing the DNS configuration to use the default DNS resolvers
Tue Mar 29 18:57:59 CEST 2016 - Flushing the local DNS cache
Tue Mar 29 18:57:59 CEST 2016 - Switching to dnscrypt if required (pause=0)
Tue Mar 29 18:57:59 CEST 2016 - dnscrypt-proxy should be (re)started, stopping previous instance if needed
Tue Mar 29 18:57:59 CEST 2016 - Stopping dnscrypt-proxy
Tue Mar 29 18:57:59 CEST 2016 - Running a test dnscrypt proxy for [dnscrypt.eu-nl using DNSCrypt over UDP]
Tue Mar 29 18:57:59 CEST 2016 - Proxy for [dnscrypt.eu-nl using DNSCrypt over UDP] is up
Tue Mar 29 18:57:59 CEST 2016 - Proxy for [dnscrypt.eu-nl using DNSCrypt over UDP] can be used
Tue Mar 29 18:58:00 CEST 2016 - Running a test dnscrypt proxy for [dnscrypt.eu-nl using DNSCrypt over TCP]
Tue Mar 29 18:58:00 CEST 2016 - Proxy for [dnscrypt.eu-nl using DNSCrypt over TCP] is up
Tue Mar 29 18:58:00 CEST 2016 - Proxy for [dnscrypt.eu-nl using DNSCrypt over TCP] can be used
Tue Mar 29 18:58:00 CEST 2016 - Plugins to be used: [ --plugin=libdcplugin_example_logging.la,/var/log/dnscrypt-query.log]
Tue Mar 29 18:58:00 CEST 2016 - Starting dnscrypt-proxy --resolver-name=dnscrypt.eu-nl
Tue Mar 29 18:58:01 CEST 2016 - Checking if the current configuration hijacks all DNS queries
Tue Mar 29 18:58:01 CEST 2016 - Current configuration doesn't seem to hijack all DNS queries
Tue Mar 29 18:58:01 CEST 2016 - Setting DNS resolvers to [127.0.0.54]
Tue Mar 29 18:58:02 CEST 2016 - Flushing local DNS cache`

**Comment by alterstep** [comment]
Can I get a bit more? So far everything looks good!

**Comment by JBey4you** [comment]
It's all that I have actually in the log. I cleared everything and did it once the again, with the image this time.

![capture d ecran 2016-03-29 a 19 02 25](https://cloud.githubusercontent.com/assets/7979756/14116616/e7a0c184-f5e0-11e5-9180-194122b73d2f.jpg)

**Comment by JBey4you** [comment]
Okay, I found the "issue". I had to enable DNSCrypt and then add 127.0.0.54 manually in the settings. Before OS X 10.11.4, this task was done automatically, even if I had custom DNS.

**Comment by jomo** [comment]
@JBey4you where did you add `127.0.0.54`? I tried both the system DNS settings and the fallback setting for DNSCrypt, but neither worked for me while Internet Sharing was enabled. Actually I think the latter caused it to constantly enable and disable dnscrypt over and over.

I'm currently on OS X 10.11.3 though, but Internet Sharing seems to be the actual culprit.

**Comment by JBey4you** [comment]
@jomo System Preferences > Network > Advanced > DNS

But I uninstalled DNSCrypt. Sometimes it works, sometimes it doesn't for no reason on OS X 10.11.4. The log seems fine, so I can't see what's the problem. I already tried to uninstall and reinstall, but it's the same thing. It works perfectly on OS X 10.11.3.

Plus, when you have DNSCrypt installed on OS X 10.11.4 (but disabled), the DNS settings don't stay. If I enter 8.8.8.8 for example, they always come back to the default one (192.168.1.1), notably after a reboot.

**Comment by D1001** [comment]
My original issue still occurs with Internet Sharing turned on after a system restart. The only way I can get DNSCrypt to work again is to turn off Internet Sharing after the restart. I can then turn Internet Sharing back on again later and it appears DNSCrypt is doing its job.
